module.exports = {
    icons:[
        {name:"fas fa-ad", title: "Ad"},
        {name:"fas fa-address-book", title: "Address book"},
        {name:"fas fa-address-card", title: "Address card"},
        {name:"fas fa-adjust", title: "Adjust"},
        {name:"fas fa-air-freshener", title: "Air freshener"},
        {name:"fas fa-align-center", title: "Align center"},
        {name:"fas fa-align-justify", title: "Align justify"},
        {name:"fas fa-align-left", title: "Align left"},
        {name:"fas fa-align-right", title: "Align right"},
        {name:"fas fa-allergies", title: "Allergies"},
        {name:"fas fa-ambulance", title: "Ambulance"},
        {name:"fas fa-american-sign-language-interpreting", title: "American sign language interpreting"},
        {name:"fas fa-anchor", title: "Anchor"},
        {name:"fas fa-angle-double-down", title: "Angle double down"},
        {name:"fas fa-angle-double-left", title: "Angle double left"},
        {name:"fas fa-angle-double-right", title: "Angle double right"},
        {name:"fas fa-angle-double-up", title: "Angle double up"},
        {name:"fas fa-angle-down", title: "Angle down"},
        {name:"fas fa-angle-left", title: "Angle left"},
        {name:"fas fa-angle-right", title: "Angle right"},
        {name:"fas fa-angle-up", title: "Angle up"},
        {name:"fas fa-angry", title: "Angry"},
        {name:"fas fa-ankh", title: "Ankh"},
        {name:"fas fa-apple-alt", title: "Apple alt"},
        {name:"fas fa-archive", title: "Archive"},
        {name:"fas fa-archway", title: "Archway"},
        {name:"fas fa-arrow-alt-circle-down", title: "Arrow alt circle down"},
        {name:"fas fa-arrow-alt-circle-left", title: "Arrow alt circle left"},
        {name:"fas fa-arrow-alt-circle-right", title: "Arrow alt circle right"},
        {name:"fas fa-arrow-alt-circle-up", title: "Arrow alt circle up"},
        {name:"fas fa-arrow-circle-down", title: "Arrow circle down"},
        {name:"fas fa-arrow-circle-left", title: "Arrow circle left"},
        {name:"fas fa-arrow-circle-right", title: "Arrow circle right"},
        {name:"fas fa-arrow-circle-up", title: "Arrow circle up"},
        {name:"fas fa-arrow-down", title: "Arrow down"},
        {name:"fas fa-arrow-left", title: "Arrow left"},
        {name:"fas fa-arrow-right", title: "Arrow right"},
        {name:"fas fa-arrow-up", title: "Arrow up"},
        {name:"fas fa-arrows-alt", title: "Arrows alt"},
        {name:"fas fa-arrows-alt-h", title: "Arrows alt h"},
        {name:"fas fa-arrows-alt-v", title: "Arrows alt v"},
        {name:"fas fa-assistive-listening-systems", title: "Assistive listening systems"},
        {name:"fas fa-asterisk", title: "Asterisk"},
        {name:"fas fa-at", title: "At"},
        {name:"fas fa-atlas", title: "Atlas"},
        {name:"fas fa-atom", title: "Atom"},
        {name:"fas fa-audio-description", title: "Audio description"},
        {name:"fas fa-award", title: "Award"},
        {name:"fas fa-baby", title: "Baby"},
        {name:"fas fa-baby-carriage", title: "Baby carriage"},
        {name:"fas fa-backspace", title: "Backspace"},
        {name:"fas fa-backward", title: "Backward"},
        {name:"fas fa-bacon", title: "Bacon"},
        {name:"fas fa-balance-scale", title: "Balance scale"},
        {name:"fas fa-balance-scale-left", title: "Balance scale left"},
        {name:"fas fa-balance-scale-right", title: "Balance scale right"},
        {name:"fas fa-ban", title: "Ban"},
        {name:"fas fa-band-aid", title: "Band aid"},
        {name:"fas fa-barcode", title: "Barcode"},
        {name:"fas fa-bars", title: "Bars"},
        {name:"fas fa-baseball-ball", title: "Baseball ball"},
        {name:"fas fa-basketball-ball", title: "Basketball ball"},
        {name:"fas fa-bath", title: "Bath"},
        {name:"fas fa-battery-empty", title: "Battery empty"},
        {name:"fas fa-battery-full", title: "Battery full"},
        {name:"fas fa-battery-half", title: "Battery half"},
        {name:"fas fa-battery-quarter", title: "Battery quarter"},
        {name:"fas fa-battery-three-quarters", title: "Battery three quarters"},
        {name:"fas fa-bed", title: "Bed"},
        {name:"fas fa-beer", title: "Beer"},
        {name:"fas fa-bell", title: "Bell"},
        {name:"fas fa-bell-slash", title: "Bell slash"},
        {name:"fas fa-bezier-curve", title: "Bezier curve"},
        {name:"fas fa-bible", title: "Bible"},
        {name:"fas fa-bicycle", title: "Bicycle"},
        {name:"fas fa-biking", title: "Biking"},
        {name:"fas fa-binoculars", title: "Binoculars"},
        {name:"fas fa-biohazard", title: "Biohazard"},
        {name:"fas fa-birthday-cake", title: "Birthday cake"},
        {name:"fas fa-blender", title: "Blender"},
        {name:"fas fa-blender-phone", title: "Blender phone"},
        {name:"fas fa-blind", title: "Blind"},
        {name:"fas fa-blog", title: "Blog"},
        {name:"fas fa-bold", title: "Bold"},
        {name:"fas fa-bolt", title: "Bolt"},
        {name:"fas fa-bomb", title: "Bomb"},
        {name:"fas fa-bone", title: "Bone"},
        {name:"fas fa-bong", title: "Bong"},
        {name:"fas fa-book", title: "Book"},
        {name:"fas fa-book-dead", title: "Book dead"},
        {name:"fas fa-book-medical", title: "Book medical"},
        {name:"fas fa-book-open", title: "Book open"},
        {name:"fas fa-book-reader", title: "Book reader"},
        {name:"fas fa-bookmark", title: "Bookmark"},
        {name:"fas fa-border-all", title: "Border all"},
        {name:"fas fa-border-none", title: "Border none"},
        {name:"fas fa-border-style", title: "Border style"},
        {name:"fas fa-bowling-ball", title: "Bowling ball"},
        {name:"fas fa-box", title: "Box"},
        {name:"fas fa-box-open", title: "Box open"},
        {name:"fas fa-boxes", title: "Boxes"},
        {name:"fas fa-braille", title: "Braille"},
        {name:"fas fa-brain", title: "Brain"},
        {name:"fas fa-bread-slice", title: "Bread slice"},
        {name:"fas fa-briefcase", title: "Briefcase"},
        {name:"fas fa-briefcase-medical", title: "Briefcase medical"},
        {name:"fas fa-broadcast-tower", title: "Broadcast tower"},
        {name:"fas fa-broom", title: "Broom"},
        {name:"fas fa-brush", title: "Brush"},
        {name:"fas fa-bug", title: "Bug"},
        {name:"fas fa-building", title: "Building"},
        {name:"fas fa-bullhorn", title: "Bullhorn"},
        {name:"fas fa-bullseye", title: "Bullseye"},
        {name:"fas fa-burn", title: "Burn"},
        {name:"fas fa-bus", title: "Bus"},
        {name:"fas fa-bus-alt", title: "Bus alt"},
        {name:"fas fa-business-time", title: "Business time"},
        {name:"fas fa-calculator", title: "Calculator"},
        {name:"fas fa-calendar", title: "Calendar"},
        {name:"fas fa-calendar-alt", title: "Calendar alt"},
        {name:"fas fa-calendar-check", title: "Calendar check"},
        {name:"fas fa-calendar-day", title: "Calendar day"},
        {name:"fas fa-calendar-minus", title: "Calendar minus"},
        {name:"fas fa-calendar-plus", title: "Calendar plus"},
        {name:"fas fa-calendar-times", title: "Calendar times"},
        {name:"fas fa-calendar-week", title: "Calendar week"},
        {name:"fas fa-camera", title: "Camera"},
        {name:"fas fa-camera-retro", title: "Camera retro"},
        {name:"fas fa-campground", title: "Campground"},
        {name:"fas fa-candy-cane", title: "Candy cane"},
        {name:"fas fa-cannabis", title: "Cannabis"},
        {name:"fas fa-capsules", title: "Capsules"},
        {name:"fas fa-car", title: "Car"},
        {name:"fas fa-car-alt", title: "Car alt"},
        {name:"fas fa-car-battery", title: "Car battery"},
        {name:"fas fa-car-crash", title: "Car crash"},
        {name:"fas fa-car-side", title: "Car side"},
        {name:"fas fa-caret-down", title: "Caret down"},
        {name:"fas fa-caret-left", title: "Caret left"},
        {name:"fas fa-caret-right", title: "Caret right"},
        {name:"fas fa-caret-square-down", title: "Caret square down"},
        {name:"fas fa-caret-square-left", title: "Caret square left"},
        {name:"fas fa-caret-square-right", title: "Caret square right"},
        {name:"fas fa-caret-square-up", title: "Caret square up"},
        {name:"fas fa-caret-up", title: "Caret up"},
        {name:"fas fa-carrot", title: "Carrot"},
        {name:"fas fa-cart-arrow-down", title: "Cart arrow down"},
        {name:"fas fa-cart-plus", title: "Cart plus"},
        {name:"fas fa-cash-register", title: "Cash register"},
        {name:"fas fa-cat", title: "Cat"},
        {name:"fas fa-certificate", title: "Certificate"},
        {name:"fas fa-chair", title: "Chair"},
        {name:"fas fa-chalkboard", title: "Chalkboard"},
        {name:"fas fa-chalkboard-teacher", title: "Chalkboard teacher"},
        {name:"fas fa-charging-station", title: "Charging station"},
        {name:"fas fa-chart-area", title: "Chart area"},
        {name:"fas fa-chart-bar", title: "Chart bar"},
        {name:"fas fa-chart-line", title: "Chart line"},
        {name:"fas fa-chart-pie", title: "Chart pie"},
        {name:"fas fa-check", title: "Check"},
        {name:"fas fa-check-circle", title: "Check circle"},
        {name:"fas fa-check-double", title: "Check double"},
        {name:"fas fa-check-square", title: "Check square"},
        {name:"fas fa-cheese", title: "Cheese"},
        {name:"fas fa-chess", title: "Chess"},
        {name:"fas fa-chess-bishop", title: "Chess bishop"},
        {name:"fas fa-chess-board", title: "Chess board"},
        {name:"fas fa-chess-king", title: "Chess king"},
        {name:"fas fa-chess-knight", title: "Chess knight"},
        {name:"fas fa-chess-pawn", title: "Chess pawn"},
        {name:"fas fa-chess-queen", title: "Chess queen"},
        {name:"fas fa-chess-rook", title: "Chess rook"},
        {name:"fas fa-chevron-circle-down", title: "Chevron circle down"},
        {name:"fas fa-chevron-circle-left", title: "Chevron circle left"},
        {name:"fas fa-chevron-circle-right", title: "Chevron circle right"},
        {name:"fas fa-chevron-circle-up", title: "Chevron circle up"},
        {name:"fas fa-chevron-down", title: "Chevron down"},
        {name:"fas fa-chevron-left", title: "Chevron left"},
        {name:"fas fa-chevron-right", title: "Chevron right"},
        {name:"fas fa-chevron-up", title: "Chevron up"},
        {name:"fas fa-child", title: "Child"},
        {name:"fas fa-church", title: "Church"},
        {name:"fas fa-circle", title: "Circle"},
        {name:"fas fa-circle-notch", title: "Circle notch"},
        {name:"fas fa-city", title: "City"},
        {name:"fas fa-clinic-medical", title: "Clinic medical"},
        {name:"fas fa-clipboard", title: "Clipboard"},
        {name:"fas fa-clipboard-check", title: "Clipboard check"},
        {name:"fas fa-clipboard-list", title: "Clipboard list"},
        {name:"fas fa-clock", title: "Clock"},
        {name:"fas fa-clone", title: "Clone"},
        {name:"fas fa-closed-captioning", title: "Closed captioning"},
        {name:"fas fa-cloud", title: "Cloud"},
        {name:"fas fa-cloud-download-alt", title: "Cloud download alt"},
        {name:"fas fa-cloud-meatball", title: "Cloud meatball"},
        {name:"fas fa-cloud-moon", title: "Cloud moon"},
        {name:"fas fa-cloud-moon-rain", title: "Cloud moon rain"},
        {name:"fas fa-cloud-rain", title: "Cloud rain"},
        {name:"fas fa-cloud-showers-heavy", title: "Cloud showers heavy"},
        {name:"fas fa-cloud-sun", title: "Cloud sun"},
        {name:"fas fa-cloud-sun-rain", title: "Cloud sun rain"},
        {name:"fas fa-cloud-upload-alt", title: "Cloud upload alt"},
        {name:"fas fa-cocktail", title: "Cocktail"},
        {name:"fas fa-code", title: "Code"},
        {name:"fas fa-code-branch", title: "Code branch"},
        {name:"fas fa-coffee", title: "Coffee"},
        {name:"fas fa-cog", title: "Cog"},
        {name:"fas fa-cogs", title: "Cogs"},
        {name:"fas fa-coins", title: "Coins"},
        {name:"fas fa-columns", title: "Columns"},
        {name:"fas fa-comment", title: "Comment"},
        {name:"fas fa-comment-alt", title: "Comment alt"},
        {name:"fas fa-comment-dollar", title: "Comment dollar"},
        {name:"fas fa-comment-dots", title: "Comment dots"},
        {name:"fas fa-comment-medical", title: "Comment medical"},
        {name:"fas fa-comment-slash", title: "Comment slash"},
        {name:"fas fa-comments", title: "Comments"},
        {name:"fas fa-comments-dollar", title: "Comments dollar"},
        {name:"fas fa-compact-disc", title: "Compact disc"},
        {name:"fas fa-compass", title: "Compass"},
        {name:"fas fa-compress", title: "Compress"},
        {name:"fas fa-compress-arrows-alt", title: "Compress arrows alt"},
        {name:"fas fa-concierge-bell", title: "Concierge bell"},
        {name:"fas fa-cookie", title: "Cookie"},
        {name:"fas fa-cookie-bite", title: "Cookie bite"},
        {name:"fas fa-copy", title: "Copy"},
        {name:"fas fa-copyright", title: "Copyright"},
        {name:"fas fa-couch", title: "Couch"},
        {name:"fas fa-credit-card", title: "Credit card"},
        {name:"fas fa-crop", title: "Crop"},
        {name:"fas fa-crop-alt", title: "Crop alt"},
        {name:"fas fa-cross", title: "Cross"},
        {name:"fas fa-crosshairs", title: "Crosshairs"},
        {name:"fas fa-crow", title: "Crow"},
        {name:"fas fa-crown", title: "Crown"},
        {name:"fas fa-crutch", title: "Crutch"},
        {name:"fas fa-cube", title: "Cube"},
        {name:"fas fa-cubes", title: "Cubes"},
        {name:"fas fa-cut", title: "Cut"},
        {name:"fas fa-database", title: "Database"},
        {name:"fas fa-deaf", title: "Deaf"},
        {name:"fas fa-democrat", title: "Democrat"},
        {name:"fas fa-desktop", title: "Desktop"},
        {name:"fas fa-dharmachakra", title: "Dharmachakra"},
        {name:"fas fa-diagnoses", title: "Diagnoses"},
        {name:"fas fa-dice", title: "Dice"},
        {name:"fas fa-dice-d20", title: "Dice d20"},
        {name:"fas fa-dice-d6", title: "Dice d6"},
        {name:"fas fa-dice-five", title: "Dice five"},
        {name:"fas fa-dice-four", title: "Dice four"},
        {name:"fas fa-dice-one", title: "Dice one"},
        {name:"fas fa-dice-six", title: "Dice six"},
        {name:"fas fa-dice-three", title: "Dice three"},
        {name:"fas fa-dice-two", title: "Dice two"},
        {name:"fas fa-digital-tachograph", title: "Digital tachograph"},
        {name:"fas fa-directions", title: "Directions"},
        {name:"fas fa-divide", title: "Divide"},
        {name:"fas fa-dizzy", title: "Dizzy"},
        {name:"fas fa-dna", title: "Dna"},
        {name:"fas fa-dog", title: "Dog"},
        {name:"fas fa-dollar-sign", title: "Dollar sign"},
        {name:"fas fa-dolly", title: "Dolly"},
        {name:"fas fa-dolly-flatbed", title: "Dolly flatbed"},
        {name:"fas fa-donate", title: "Donate"},
        {name:"fas fa-door-closed", title: "Door closed"},
        {name:"fas fa-door-open", title: "Door open"},
        {name:"fas fa-dot-circle", title: "Dot circle"},
        {name:"fas fa-dove", title: "Dove"},
        {name:"fas fa-download", title: "Download"},
        {name:"fas fa-drafting-compass", title: "Drafting compass"},
        {name:"fas fa-dragon", title: "Dragon"},
        {name:"fas fa-draw-polygon", title: "Draw polygon"},
        {name:"fas fa-drum", title: "Drum"},
        {name:"fas fa-drum-steelpan", title: "Drum steelpan"},
        {name:"fas fa-drumstick-bite", title: "Drumstick bite"},
        {name:"fas fa-dumbbell", title: "Dumbbell"},
        {name:"fas fa-dumpster", title: "Dumpster"},
        {name:"fas fa-dumpster-fire", title: "Dumpster fire"},
        {name:"fas fa-dungeon", title: "Dungeon"},
        {name:"fas fa-edit", title: "Edit"},
        {name:"fas fa-egg", title: "Egg"},
        {name:"fas fa-eject", title: "Eject"},
        {name:"fas fa-ellipsis-h", title: "Ellipsis h"},
        {name:"fas fa-ellipsis-v", title: "Ellipsis v"},
        {name:"fas fa-envelope", title: "Envelope"},
        {name:"fas fa-envelope-open", title: "Envelope open"},
        {name:"fas fa-envelope-open-text", title: "Envelope open text"},
        {name:"fas fa-envelope-square", title: "Envelope square"},
        {name:"fas fa-equals", title: "Equals"},
        {name:"fas fa-eraser", title: "Eraser"},
        {name:"fas fa-ethernet", title: "Ethernet"},
        {name:"fas fa-euro-sign", title: "Euro sign"},
        {name:"fas fa-exchange-alt", title: "Exchange alt"},
        {name:"fas fa-exclamation", title: "Exclamation"},
        {name:"fas fa-exclamation-circle", title: "Exclamation circle"},
        {name:"fas fa-exclamation-triangle", title: "Exclamation triangle"},
        {name:"fas fa-expand", title: "Expand"},
        {name:"fas fa-expand-arrows-alt", title: "Expand arrows alt"},
        {name:"fas fa-external-link-alt", title: "External link alt"},
        {name:"fas fa-external-link-square-alt", title: "External link square alt"},
        {name:"fas fa-eye", title: "Eye"},
        {name:"fas fa-eye-dropper", title: "Eye dropper"},
        {name:"fas fa-eye-slash", title: "Eye slash"},
        {name:"fas fa-fan", title: "Fan"},
        {name:"fas fa-fast-backward", title: "Fast backward"},
        {name:"fas fa-fast-forward", title: "Fast forward"},
        {name:"fas fa-fax", title: "Fax"},
        {name:"fas fa-feather", title: "Feather"},
        {name:"fas fa-feather-alt", title: "Feather alt"},
        {name:"fas fa-female", title: "Female"},
        {name:"fas fa-fighter-jet", title: "Fighter jet"},
        {name:"fas fa-file", title: "File"},
        {name:"fas fa-file-alt", title: "File alt"},
        {name:"fas fa-file-archive", title: "File archive"},
        {name:"fas fa-file-audio", title: "File audio"},
        {name:"fas fa-file-code", title: "File code"},
        {name:"fas fa-file-contract", title: "File contract"},
        {name:"fas fa-file-csv", title: "File csv"},
        {name:"fas fa-file-download", title: "File download"},
        {name:"fas fa-file-excel", title: "File excel"},
        {name:"fas fa-file-export", title: "File export"},
        {name:"fas fa-file-image", title: "File image"},
        {name:"fas fa-file-import", title: "File import"},
        {name:"fas fa-file-invoice", title: "File invoice"},
        {name:"fas fa-file-invoice-dollar", title: "File invoice dollar"},
        {name:"fas fa-file-medical", title: "File medical"},
        {name:"fas fa-file-medical-alt", title: "File medical alt"},
        {name:"fas fa-file-pdf", title: "File pdf"},
        {name:"fas fa-file-powerpoint", title: "File powerpoint"},
        {name:"fas fa-file-prescription", title: "File prescription"},
        {name:"fas fa-file-signature", title: "File signature"},
        {name:"fas fa-file-upload", title: "File upload"},
        {name:"fas fa-file-video", title: "File video"},
        {name:"fas fa-file-word", title: "File word"},
        {name:"fas fa-fill", title: "Fill"},
        {name:"fas fa-fill-drip", title: "Fill drip"},
        {name:"fas fa-film", title: "Film"},
        {name:"fas fa-filter", title: "Filter"},
        {name:"fas fa-fingerprint", title: "Fingerprint"},
        {name:"fas fa-fire", title: "Fire"},
        {name:"fas fa-fire-alt", title: "Fire alt"},
        {name:"fas fa-fire-extinguisher", title: "Fire extinguisher"},
        {name:"fas fa-first-aid", title: "First aid"},
        {name:"fas fa-fish", title: "Fish"},
        {name:"fas fa-fist-raised", title: "Fist raised"},
        {name:"fas fa-flag", title: "Flag"},
        {name:"fas fa-flag-checkered", title: "Flag checkered"},
        {name:"fas fa-flag-usa", title: "Flag usa"},
        {name:"fas fa-flask", title: "Flask"},
        {name:"fas fa-flushed", title: "Flushed"},
        {name:"fas fa-folder", title: "Folder"},
        {name:"fas fa-folder-minus", title: "Folder minus"},
        {name:"fas fa-folder-open", title: "Folder open"},
        {name:"fas fa-folder-plus", title: "Folder plus"},
        {name:"fas fa-font", title: "Font"},
        {name:"fas fa-football-ball", title: "Football ball"},
        {name:"fas fa-forward", title: "Forward"},
        {name:"fas fa-frog", title: "Frog"},
        {name:"fas fa-frown", title: "Frown"},
        {name:"fas fa-frown-open", title: "Frown open"},
        {name:"fas fa-funnel-dollar", title: "Funnel dollar"},
        {name:"fas fa-futbol", title: "Futbol"},
        {name:"fas fa-gamepad", title: "Gamepad"},
        {name:"fas fa-gas-pump", title: "Gas pump"},
        {name:"fas fa-gavel", title: "Gavel"},
        {name:"fas fa-gem", title: "Gem"},
        {name:"fas fa-genderless", title: "Genderless"},
        {name:"fas fa-ghost", title: "Ghost"},
        {name:"fas fa-gift", title: "Gift"},
        {name:"fas fa-gifts", title: "Gifts"},
        {name:"fas fa-glass-cheers", title: "Glass cheers"},
        {name:"fas fa-glass-martini", title: "Glass martini"},
        {name:"fas fa-glass-martini-alt", title: "Glass martini alt"},
        {name:"fas fa-glass-whiskey", title: "Glass whiskey"},
        {name:"fas fa-glasses", title: "Glasses"},
        {name:"fas fa-globe", title: "Globe"},
        {name:"fas fa-globe-africa", title: "Globe africa"},
        {name:"fas fa-globe-americas", title: "Globe americas"},
        {name:"fas fa-globe-asia", title: "Globe asia"},
        {name:"fas fa-globe-europe", title: "Globe europe"},
        {name:"fas fa-golf-ball", title: "Golf ball"},
        {name:"fas fa-gopuram", title: "Gopuram"},
        {name:"fas fa-graduation-cap", title: "Graduation cap"},
        {name:"fas fa-greater-than", title: "Greater than"},
        {name:"fas fa-greater-than-equal", title: "Greater than equal"},
        {name:"fas fa-grimace", title: "Grimace"},
        {name:"fas fa-grin", title: "Grin"},
        {name:"fas fa-grin-alt", title: "Grin alt"},
        {name:"fas fa-grin-beam", title: "Grin beam"},
        {name:"fas fa-grin-beam-sweat", title: "Grin beam sweat"},
        {name:"fas fa-grin-hearts", title: "Grin hearts"},
        {name:"fas fa-grin-squint", title: "Grin squint"},
        {name:"fas fa-grin-squint-tears", title: "Grin squint tears"},
        {name:"fas fa-grin-stars", title: "Grin stars"},
        {name:"fas fa-grin-tears", title: "Grin tears"},
        {name:"fas fa-grin-tongue", title: "Grin tongue"},
        {name:"fas fa-grin-tongue-squint", title: "Grin tongue squint"},
        {name:"fas fa-grin-tongue-wink", title: "Grin tongue wink"},
        {name:"fas fa-grin-wink", title: "Grin wink"},
        {name:"fas fa-grip-horizontal", title: "Grip horizontal"},
        {name:"fas fa-grip-lines", title: "Grip lines"},
        {name:"fas fa-grip-lines-vertical", title: "Grip lines vertical"},
        {name:"fas fa-grip-vertical", title: "Grip vertical"},
        {name:"fas fa-guitar", title: "Guitar"},
        {name:"fas fa-h-square", title: "H square"},
        {name:"fas fa-hamburger", title: "Hamburger"},
        {name:"fas fa-hammer", title: "Hammer"},
        {name:"fas fa-hamsa", title: "Hamsa"},
        {name:"fas fa-hand-holding", title: "Hand holding"},
        {name:"fas fa-hand-holding-heart", title: "Hand holding heart"},
        {name:"fas fa-hand-holding-usd", title: "Hand holding usd"},
        {name:"fas fa-hand-lizard", title: "Hand lizard"},
        {name:"fas fa-hand-middle-finger", title: "Hand middle finger"},
        {name:"fas fa-hand-paper", title: "Hand paper"},
        {name:"fas fa-hand-peace", title: "Hand peace"},
        {name:"fas fa-hand-point-down", title: "Hand point down"},
        {name:"fas fa-hand-point-left", title: "Hand point left"},
        {name:"fas fa-hand-point-right", title: "Hand point right"},
        {name:"fas fa-hand-point-up", title: "Hand point up"},
        {name:"fas fa-hand-pointer", title: "Hand pointer"},
        {name:"fas fa-hand-rock", title: "Hand rock"},
        {name:"fas fa-hand-scissors", title: "Hand scissors"},
        {name:"fas fa-hand-spock", title: "Hand spock"},
        {name:"fas fa-hands", title: "Hands"},
        {name:"fas fa-hands-helping", title: "Hands helping"},
        {name:"fas fa-handshake", title: "Handshake"},
        {name:"fas fa-hanukiah", title: "Hanukiah"},
        {name:"fas fa-hard-hat", title: "Hard hat"},
        {name:"fas fa-hashtag", title: "Hashtag"},
        {name:"fas fa-hat-cowboy", title: "Hat cowboy"},
        {name:"fas fa-hat-cowboy-side", title: "Hat cowboy side"},
        {name:"fas fa-hat-wizard", title: "Hat wizard"},
        {name:"fas fa-haykal", title: "Haykal"},
        {name:"fas fa-hdd", title: "Hdd"},
        {name:"fas fa-heading", title: "Heading"},
        {name:"fas fa-headphones", title: "Headphones"},
        {name:"fas fa-headphones-alt", title: "Headphones alt"},
        {name:"fas fa-headset", title: "Headset"},
        {name:"fas fa-heart", title: "Heart"},
        {name:"fas fa-heart-broken", title: "Heart broken"},
        {name:"fas fa-heartbeat", title: "Heartbeat"},
        {name:"fas fa-helicopter", title: "Helicopter"},
        {name:"fas fa-highlighter", title: "Highlighter"},
        {name:"fas fa-hiking", title: "Hiking"},
        {name:"fas fa-hippo", title: "Hippo"},
        {name:"fas fa-history", title: "History"},
        {name:"fas fa-hockey-puck", title: "Hockey puck"},
        {name:"fas fa-holly-berry", title: "Holly berry"},
        {name:"fas fa-home", title: "Home"},
        {name:"fas fa-horse", title: "Horse"},
        {name:"fas fa-horse-head", title: "Horse head"},
        {name:"fas fa-hospital", title: "Hospital"},
        {name:"fas fa-hospital-alt", title: "Hospital alt"},
        {name:"fas fa-hospital-symbol", title: "Hospital symbol"},
        {name:"fas fa-hot-tub", title: "Hot tub"},
        {name:"fas fa-hotdog", title: "Hotdog"},
        {name:"fas fa-hotel", title: "Hotel"},
        {name:"fas fa-hourglass", title: "Hourglass"},
        {name:"fas fa-hourglass-end", title: "Hourglass end"},
        {name:"fas fa-hourglass-half", title: "Hourglass half"},
        {name:"fas fa-hourglass-start", title: "Hourglass start"},
        {name:"fas fa-house-damage", title: "House damage"},
        {name:"fas fa-hryvnia", title: "Hryvnia"},
        {name:"fas fa-i-cursor", title: "I cursor"},
        {name:"fas fa-ice-cream", title: "Ice cream"},
        {name:"fas fa-icicles", title: "Icicles"},
        {name:"fas fa-icons", title: "Icons"},
        {name:"fas fa-id-badge", title: "Id badge"},
        {name:"fas fa-id-card", title: "Id card"},
        {name:"fas fa-id-card-alt", title: "Id card alt"},
        {name:"fas fa-igloo", title: "Igloo"},
        {name:"fas fa-image", title: "Image"},
        {name:"fas fa-images", title: "Images"},
        {name:"fas fa-inbox", title: "Inbox"},
        {name:"fas fa-indent", title: "Indent"},
        {name:"fas fa-industry", title: "Industry"},
        {name:"fas fa-infinity", title: "Infinity"},
        {name:"fas fa-info", title: "Info"},
        {name:"fas fa-info-circle", title: "Info circle"},
        {name:"fas fa-italic", title: "Italic"},
        {name:"fas fa-jedi", title: "Jedi"},
        {name:"fas fa-joint", title: "Joint"},
        {name:"fas fa-journal-whills", title: "Journal whills"},
        {name:"fas fa-kaaba", title: "Kaaba"},
        {name:"fas fa-key", title: "Key"},
        {name:"fas fa-keyboard", title: "Keyboard"},
        {name:"fas fa-khanda", title: "Khanda"},
        {name:"fas fa-kiss", title: "Kiss"},
        {name:"fas fa-kiss-beam", title: "Kiss beam"},
        {name:"fas fa-kiss-wink-heart", title: "Kiss wink heart"},
        {name:"fas fa-kiwi-bird", title: "Kiwi bird"},
        {name:"fas fa-landmark", title: "Landmark"},
        {name:"fas fa-language", title: "Language"},
        {name:"fas fa-laptop", title: "Laptop"},
        {name:"fas fa-laptop-code", title: "Laptop code"},
        {name:"fas fa-laptop-medical", title: "Laptop medical"},
        {name:"fas fa-laugh", title: "Laugh"},
        {name:"fas fa-laugh-beam", title: "Laugh beam"},
        {name:"fas fa-laugh-squint", title: "Laugh squint"},
        {name:"fas fa-laugh-wink", title: "Laugh wink"},
        {name:"fas fa-layer-group", title: "Layer group"},
        {name:"fas fa-leaf", title: "Leaf"},
        {name:"fas fa-lemon", title: "Lemon"},
        {name:"fas fa-less-than", title: "Less than"},
        {name:"fas fa-less-than-equal", title: "Less than equal"},
        {name:"fas fa-level-down-alt", title: "Level down alt"},
        {name:"fas fa-level-up-alt", title: "Level up alt"},
        {name:"fas fa-life-ring", title: "Life ring"},
        {name:"fas fa-lightbulb", title: "Lightbulb"},
        {name:"fas fa-link", title: "Link"},
        {name:"fas fa-lira-sign", title: "Lira sign"},
        {name:"fas fa-list", title: "List"},
        {name:"fas fa-list-alt", title: "List alt"},
        {name:"fas fa-list-ol", title: "List ol"},
        {name:"fas fa-list-ul", title: "List ul"},
        {name:"fas fa-location-arrow", title: "Location arrow"},
        {name:"fas fa-lock", title: "Lock"},
        {name:"fas fa-lock-open", title: "Lock open"},
        {name:"fas fa-long-arrow-alt-down", title: "Long arrow alt down"},
        {name:"fas fa-long-arrow-alt-left", title: "Long arrow alt left"},
        {name:"fas fa-long-arrow-alt-right", title: "Long arrow alt right"},
        {name:"fas fa-long-arrow-alt-up", title: "Long arrow alt up"},
        {name:"fas fa-low-vision", title: "Low vision"},
        {name:"fas fa-luggage-cart", title: "Luggage cart"},
        {name:"fas fa-magic", title: "Magic"},
        {name:"fas fa-magnet", title: "Magnet"},
        {name:"fas fa-mail-bulk", title: "Mail bulk"},
        {name:"fas fa-male", title: "Male"},
        {name:"fas fa-map", title: "Map"},
        {name:"fas fa-map-marked", title: "Map marked"},
        {name:"fas fa-map-marked-alt", title: "Map marked alt"},
        {name:"fas fa-map-marker", title: "Map marker"},
        {name:"fas fa-map-marker-alt", title: "Map marker alt"},
        {name:"fas fa-map-pin", title: "Map pin"},
        {name:"fas fa-map-signs", title: "Map signs"},
        {name:"fas fa-marker", title: "Marker"},
        {name:"fas fa-mars", title: "Mars"},
        {name:"fas fa-mars-double", title: "Mars double"},
        {name:"fas fa-mars-stroke", title: "Mars stroke"},
        {name:"fas fa-mars-stroke-h", title: "Mars stroke h"},
        {name:"fas fa-mars-stroke-v", title: "Mars stroke v"},
        {name:"fas fa-mask", title: "Mask"},
        {name:"fas fa-medal", title: "Medal"},
        {name:"fas fa-medkit", title: "Medkit"},
        {name:"fas fa-meh", title: "Meh"},
        {name:"fas fa-meh-blank", title: "Meh blank"},
        {name:"fas fa-meh-rolling-eyes", title: "Meh rolling eyes"},
        {name:"fas fa-memory", title: "Memory"},
        {name:"fas fa-menorah", title: "Menorah"},
        {name:"fas fa-mercury", title: "Mercury"},
        {name:"fas fa-meteor", title: "Meteor"},
        {name:"fas fa-microchip", title: "Microchip"},
        {name:"fas fa-microphone", title: "Microphone"},
        {name:"fas fa-microphone-alt", title: "Microphone alt"},
        {name:"fas fa-microphone-alt-slash", title: "Microphone alt slash"},
        {name:"fas fa-microphone-slash", title: "Microphone slash"},
        {name:"fas fa-microscope", title: "Microscope"},
        {name:"fas fa-minus", title: "Minus"},
        {name:"fas fa-minus-circle", title: "Minus circle"},
        {name:"fas fa-minus-square", title: "Minus square"},
        {name:"fas fa-mitten", title: "Mitten"},
        {name:"fas fa-mobile", title: "Mobile"},
        {name:"fas fa-mobile-alt", title: "Mobile alt"},
        {name:"fas fa-money-bill", title: "Money bill"},
        {name:"fas fa-money-bill-alt", title: "Money bill alt"},
        {name:"fas fa-money-bill-wave", title: "Money bill wave"},
        {name:"fas fa-money-bill-wave-alt", title: "Money bill wave alt"},
        {name:"fas fa-money-check", title: "Money check"},
        {name:"fas fa-money-check-alt", title: "Money check alt"},
        {name:"fas fa-monument", title: "Monument"},
        {name:"fas fa-moon", title: "Moon"},
        {name:"fas fa-mortar-pestle", title: "Mortar pestle"},
        {name:"fas fa-mosque", title: "Mosque"},
        {name:"fas fa-motorcycle", title: "Motorcycle"},
        {name:"fas fa-mountain", title: "Mountain"},
        {name:"fas fa-mouse", title: "Mouse"},
        {name:"fas fa-mouse-pointer", title: "Mouse pointer"},
        {name:"fas fa-mug-hot", title: "Mug hot"},
        {name:"fas fa-music", title: "Music"},
        {name:"fas fa-network-wired", title: "Network wired"},
        {name:"fas fa-neuter", title: "Neuter"},
        {name:"fas fa-newspaper", title: "Newspaper"},
        {name:"fas fa-not-equal", title: "Not equal"},
        {name:"fas fa-notes-medical", title: "Notes medical"},
        {name:"fas fa-object-group", title: "Object group"},
        {name:"fas fa-object-ungroup", title: "Object ungroup"},
        {name:"fas fa-oil-can", title: "Oil can"},
        {name:"fas fa-om", title: "Om"},
        {name:"fas fa-otter", title: "Otter"},
        {name:"fas fa-outdent", title: "Outdent"},
        {name:"fas fa-pager", title: "Pager"},
        {name:"fas fa-paint-brush", title: "Paint brush"},
        {name:"fas fa-paint-roller", title: "Paint roller"},
        {name:"fas fa-palette", title: "Palette"},
        {name:"fas fa-pallet", title: "Pallet"},
        {name:"fas fa-paper-plane", title: "Paper plane"},
        {name:"fas fa-paperclip", title: "Paperclip"},
        {name:"fas fa-parachute-box", title: "Parachute box"},
        {name:"fas fa-paragraph", title: "Paragraph"},
        {name:"fas fa-parking", title: "Parking"},
        {name:"fas fa-passport", title: "Passport"},
        {name:"fas fa-pastafarianism", title: "Pastafarianism"},
        {name:"fas fa-paste", title: "Paste"},
        {name:"fas fa-pause", title: "Pause"},
        {name:"fas fa-pause-circle", title: "Pause circle"},
        {name:"fas fa-paw", title: "Paw"},
        {name:"fas fa-peace", title: "Peace"},
        {name:"fas fa-pen", title: "Pen"},
        {name:"fas fa-pen-alt", title: "Pen alt"},
        {name:"fas fa-pen-fancy", title: "Pen fancy"},
        {name:"fas fa-pen-nib", title: "Pen nib"},
        {name:"fas fa-pen-square", title: "Pen square"},
        {name:"fas fa-pencil-alt", title: "Pencil alt"},
        {name:"fas fa-pencil-ruler", title: "Pencil ruler"},
        {name:"fas fa-people-carry", title: "People carry"},
        {name:"fas fa-pepper-hot", title: "Pepper hot"},
        {name:"fas fa-percent", title: "Percent"},
        {name:"fas fa-percentage", title: "Percentage"},
        {name:"fas fa-person-booth", title: "Person booth"},
        {name:"fas fa-phone", title: "Phone"},
        {name:"fas fa-phone-alt", title: "Phone alt"},
        {name:"fas fa-phone-slash", title: "Phone slash"},
        {name:"fas fa-phone-square", title: "Phone square"},
        {name:"fas fa-phone-square-alt", title: "Phone square alt"},
        {name:"fas fa-phone-volume", title: "Phone volume"},
        {name:"fas fa-photo-video", title: "Photo video"},
        {name:"fas fa-piggy-bank", title: "Piggy bank"},
        {name:"fas fa-pills", title: "Pills"},
        {name:"fas fa-pizza-slice", title: "Pizza slice"},
        {name:"fas fa-place-of-worship", title: "Place of worship"},
        {name:"fas fa-plane", title: "Plane"},
        {name:"fas fa-plane-arrival", title: "Plane arrival"},
        {name:"fas fa-plane-departure", title: "Plane departure"},
        {name:"fas fa-play", title: "Play"},
        {name:"fas fa-play-circle", title: "Play circle"},
        {name:"fas fa-plug", title: "Plug"},
        {name:"fas fa-plus", title: "Plus"},
        {name:"fas fa-plus-circle", title: "Plus circle"},
        {name:"fas fa-plus-square", title: "Plus square"},
        {name:"fas fa-podcast", title: "Podcast"},
        {name:"fas fa-poll", title: "Poll"},
        {name:"fas fa-poll-h", title: "Poll h"},
        {name:"fas fa-poo", title: "Poo"},
        {name:"fas fa-poo-storm", title: "Poo storm"},
        {name:"fas fa-poop", title: "Poop"},
        {name:"fas fa-portrait", title: "Portrait"},
        {name:"fas fa-pound-sign", title: "Pound sign"},
        {name:"fas fa-power-off", title: "Power off"},
        {name:"fas fa-pray", title: "Pray"},
        {name:"fas fa-praying-hands", title: "Praying hands"},
        {name:"fas fa-prescription", title: "Prescription"},
        {name:"fas fa-prescription-bottle", title: "Prescription bottle"},
        {name:"fas fa-prescription-bottle-alt", title: "Prescription bottle alt"},
        {name:"fas fa-print", title: "Print"},
        {name:"fas fa-procedures", title: "Procedures"},
        {name:"fas fa-project-diagram", title: "Project diagram"},
        {name:"fas fa-puzzle-piece", title: "Puzzle piece"},
        {name:"fas fa-qrcode", title: "Qrcode"},
        {name:"fas fa-question", title: "Question"},
        {name:"fas fa-question-circle", title: "Question circle"},
        {name:"fas fa-quidditch", title: "Quidditch"},
        {name:"fas fa-quote-left", title: "Quote left"},
        {name:"fas fa-quote-right", title: "Quote right"},
        {name:"fas fa-quran", title: "Quran"},
        {name:"fas fa-radiation", title: "Radiation"},
        {name:"fas fa-radiation-alt", title: "Radiation alt"},
        {name:"fas fa-rainbow", title: "Rainbow"},
        {name:"fas fa-random", title: "Random"},
        {name:"fas fa-receipt", title: "Receipt"},
        {name:"fas fa-record-vinyl", title: "Record vinyl"},
        {name:"fas fa-recycle", title: "Recycle"},
        {name:"fas fa-redo", title: "Redo"},
        {name:"fas fa-redo-alt", title: "Redo alt"},
        {name:"fas fa-registered", title: "Registered"},
        {name:"fas fa-remove-format", title: "Remove format"},
        {name:"fas fa-reply", title: "Reply"},
        {name:"fas fa-reply-all", title: "Reply all"},
        {name:"fas fa-republican", title: "Republican"},
        {name:"fas fa-restroom", title: "Restroom"},
        {name:"fas fa-retweet", title: "Retweet"},
        {name:"fas fa-ribbon", title: "Ribbon"},
        {name:"fas fa-ring", title: "Ring"},
        {name:"fas fa-road", title: "Road"},
        {name:"fas fa-robot", title: "Robot"},
        {name:"fas fa-rocket", title: "Rocket"},
        {name:"fas fa-route", title: "Route"},
        {name:"fas fa-rss", title: "Rss"},
        {name:"fas fa-rss-square", title: "Rss square"},
        {name:"fas fa-ruble-sign", title: "Ruble sign"},
        {name:"fas fa-ruler", title: "Ruler"},
        {name:"fas fa-ruler-combined", title: "Ruler combined"},
        {name:"fas fa-ruler-horizontal", title: "Ruler horizontal"},
        {name:"fas fa-ruler-vertical", title: "Ruler vertical"},
        {name:"fas fa-running", title: "Running"},
        {name:"fas fa-rupee-sign", title: "Rupee sign"},
        {name:"fas fa-sad-cry", title: "Sad cry"},
        {name:"fas fa-sad-tear", title: "Sad tear"},
        {name:"fas fa-satellite", title: "Satellite"},
        {name:"fas fa-satellite-dish", title: "Satellite dish"},
        {name:"fas fa-save", title: "Save"},
        {name:"fas fa-school", title: "School"},
        {name:"fas fa-screwdriver", title: "Screwdriver"},
        {name:"fas fa-scroll", title: "Scroll"},
        {name:"fas fa-sd-card", title: "Sd card"},
        {name:"fas fa-search", title: "Search"},
        {name:"fas fa-search-dollar", title: "Search dollar"},
        {name:"fas fa-search-location", title: "Search location"},
        {name:"fas fa-search-minus", title: "Search minus"},
        {name:"fas fa-search-plus", title: "Search plus"},
        {name:"fas fa-seedling", title: "Seedling"},
        {name:"fas fa-server", title: "Server"},
        {name:"fas fa-shapes", title: "Shapes"},
        {name:"fas fa-share", title: "Share"},
        {name:"fas fa-share-alt", title: "Share alt"},
        {name:"fas fa-share-alt-square", title: "Share alt square"},
        {name:"fas fa-share-square", title: "Share square"},
        {name:"fas fa-shekel-sign", title: "Shekel sign"},
        {name:"fas fa-shield-alt", title: "Shield alt"},
        {name:"fas fa-ship", title: "Ship"},
        {name:"fas fa-shipping-fast", title: "Shipping fast"},
        {name:"fas fa-shoe-prints", title: "Shoe prints"},
        {name:"fas fa-shopping-bag", title: "Shopping bag"},
        {name:"fas fa-shopping-basket", title: "Shopping basket"},
        {name:"fas fa-shopping-cart", title: "Shopping cart"},
        {name:"fas fa-shower", title: "Shower"},
        {name:"fas fa-shuttle-van", title: "Shuttle van"},
        {name:"fas fa-sign", title: "Sign"},
        {name:"fas fa-sign-in-alt", title: "Sign in alt"},
        {name:"fas fa-sign-language", title: "Sign language"},
        {name:"fas fa-sign-out-alt", title: "Sign out alt"},
        {name:"fas fa-signal", title: "Signal"},
        {name:"fas fa-signature", title: "Signature"},
        {name:"fas fa-sim-card", title: "Sim card"},
        {name:"fas fa-sitemap", title: "Sitemap"},
        {name:"fas fa-skating", title: "Skating"},
        {name:"fas fa-skiing", title: "Skiing"},
        {name:"fas fa-skiing-nordic", title: "Skiing nordic"},
        {name:"fas fa-skull", title: "Skull"},
        {name:"fas fa-skull-crossbones", title: "Skull crossbones"},
        {name:"fas fa-slash", title: "Slash"},
        {name:"fas fa-sleigh", title: "Sleigh"},
        {name:"fas fa-sliders-h", title: "Sliders h"},
        {name:"fas fa-smile", title: "Smile"},
        {name:"fas fa-smile-beam", title: "Smile beam"},
        {name:"fas fa-smile-wink", title: "Smile wink"},
        {name:"fas fa-smog", title: "Smog"},
        {name:"fas fa-smoking", title: "Smoking"},
        {name:"fas fa-smoking-ban", title: "Smoking ban"},
        {name:"fas fa-sms", title: "Sms"},
        {name:"fas fa-snowboarding", title: "Snowboarding"},
        {name:"fas fa-snowflake", title: "Snowflake"},
        {name:"fas fa-snowman", title: "Snowman"},
        {name:"fas fa-snowplow", title: "Snowplow"},
        {name:"fas fa-socks", title: "Socks"},
        {name:"fas fa-solar-panel", title: "Solar panel"},
        {name:"fas fa-sort", title: "Sort"},
        {name:"fas fa-sort-alpha-down", title: "Sort alpha down"},
        {name:"fas fa-sort-alpha-down-alt", title: "Sort alpha down alt"},
        {name:"fas fa-sort-alpha-up", title: "Sort alpha up"},
        {name:"fas fa-sort-alpha-up-alt", title: "Sort alpha up alt"},
        {name:"fas fa-sort-amount-down", title: "Sort amount down"},
        {name:"fas fa-sort-amount-down-alt", title: "Sort amount down alt"},
        {name:"fas fa-sort-amount-up", title: "Sort amount up"},
        {name:"fas fa-sort-amount-up-alt", title: "Sort amount up alt"},
        {name:"fas fa-sort-down", title: "Sort down"},
        {name:"fas fa-sort-numeric-down", title: "Sort numeric down"},
        {name:"fas fa-sort-numeric-down-alt", title: "Sort numeric down alt"},
        {name:"fas fa-sort-numeric-up", title: "Sort numeric up"},
        {name:"fas fa-sort-numeric-up-alt", title: "Sort numeric up alt"},
        {name:"fas fa-sort-up", title: "Sort up"},
        {name:"fas fa-spa", title: "Spa"},
        {name:"fas fa-space-shuttle", title: "Space shuttle"},
        {name:"fas fa-spell-check", title: "Spell check"},
        {name:"fas fa-spider", title: "Spider"},
        {name:"fas fa-spinner", title: "Spinner"},
        {name:"fas fa-splotch", title: "Splotch"},
        {name:"fas fa-spray-can", title: "Spray can"},
        {name:"fas fa-square", title: "Square"},
        {name:"fas fa-square-full", title: "Square full"},
        {name:"fas fa-square-root-alt", title: "Square root alt"},
        {name:"fas fa-stamp", title: "Stamp"},
        {name:"fas fa-star", title: "Star"},
        {name:"fas fa-star-and-crescent", title: "Star and crescent"},
        {name:"fas fa-star-half", title: "Star half"},
        {name:"fas fa-star-half-alt", title: "Star half alt"},
        {name:"fas fa-star-of-david", title: "Star of david"},
        {name:"fas fa-star-of-life", title: "Star of life"},
        {name:"fas fa-step-backward", title: "Step backward"},
        {name:"fas fa-step-forward", title: "Step forward"},
        {name:"fas fa-stethoscope", title: "Stethoscope"},
        {name:"fas fa-sticky-note", title: "Sticky note"},
        {name:"fas fa-stop", title: "Stop"},
        {name:"fas fa-stop-circle", title: "Stop circle"},
        {name:"fas fa-stopwatch", title: "Stopwatch"},
        {name:"fas fa-store", title: "Store"},
        {name:"fas fa-store-alt", title: "Store alt"},
        {name:"fas fa-stream", title: "Stream"},
        {name:"fas fa-street-view", title: "Street view"},
        {name:"fas fa-strikethrough", title: "Strikethrough"},
        {name:"fas fa-stroopwafel", title: "Stroopwafel"},
        {name:"fas fa-subscript", title: "Subscript"},
        {name:"fas fa-subway", title: "Subway"},
        {name:"fas fa-suitcase", title: "Suitcase"},
        {name:"fas fa-suitcase-rolling", title: "Suitcase rolling"},
        {name:"fas fa-sun", title: "Sun"},
        {name:"fas fa-superscript", title: "Superscript"},
        {name:"fas fa-surprise", title: "Surprise"},
        {name:"fas fa-swatchbook", title: "Swatchbook"},
        {name:"fas fa-swimmer", title: "Swimmer"},
        {name:"fas fa-swimming-pool", title: "Swimming pool"},
        {name:"fas fa-synagogue", title: "Synagogue"},
        {name:"fas fa-sync", title: "Sync"},
        {name:"fas fa-sync-alt", title: "Sync alt"},
        {name:"fas fa-syringe", title: "Syringe"},
        {name:"fas fa-table", title: "Table"},
        {name:"fas fa-table-tennis", title: "Table tennis"},
        {name:"fas fa-tablet", title: "Tablet"},
        {name:"fas fa-tablet-alt", title: "Tablet alt"},
        {name:"fas fa-tablets", title: "Tablets"},
        {name:"fas fa-tachometer-alt", title: "Tachometer alt"},
        {name:"fas fa-tag", title: "Tag"},
        {name:"fas fa-tags", title: "Tags"},
        {name:"fas fa-tape", title: "Tape"},
        {name:"fas fa-tasks", title: "Tasks"},
        {name:"fas fa-taxi", title: "Taxi"},
        {name:"fas fa-teeth", title: "Teeth"},
        {name:"fas fa-teeth-open", title: "Teeth open"},
        {name:"fas fa-temperature-high", title: "Temperature high"},
        {name:"fas fa-temperature-low", title: "Temperature low"},
        {name:"fas fa-tenge", title: "Tenge"},
        {name:"fas fa-terminal", title: "Terminal"},
        {name:"fas fa-text-height", title: "Text height"},
        {name:"fas fa-text-width", title: "Text width"},
        {name:"fas fa-th", title: "Th"},
        {name:"fas fa-th-large", title: "Th large"},
        {name:"fas fa-th-list", title: "Th list"},
        {name:"fas fa-theater-masks", title: "Theater masks"},
        {name:"fas fa-thermometer", title: "Thermometer"},
        {name:"fas fa-thermometer-empty", title: "Thermometer empty"},
        {name:"fas fa-thermometer-full", title: "Thermometer full"},
        {name:"fas fa-thermometer-half", title: "Thermometer half"},
        {name:"fas fa-thermometer-quarter", title: "Thermometer quarter"},
        {name:"fas fa-thermometer-three-quarters", title: "Thermometer three quarters"},
        {name:"fas fa-thumbs-down", title: "Thumbs down"},
        {name:"fas fa-thumbs-up", title: "Thumbs up"},
        {name:"fas fa-thumbtack", title: "Thumbtack"},
        {name:"fas fa-ticket-alt", title: "Ticket alt"},
        {name:"fas fa-times", title: "Times"},
        {name:"fas fa-times-circle", title: "Times circle"},
        {name:"fas fa-tint", title: "Tint"},
        {name:"fas fa-tint-slash", title: "Tint slash"},
        {name:"fas fa-tired", title: "Tired"},
        {name:"fas fa-toggle-off", title: "Toggle off"},
        {name:"fas fa-toggle-on", title: "Toggle on"},
        {name:"fas fa-toilet", title: "Toilet"},
        {name:"fas fa-toilet-paper", title: "Toilet paper"},
        {name:"fas fa-toolbox", title: "Toolbox"},
        {name:"fas fa-tools", title: "Tools"},
        {name:"fas fa-tooth", title: "Tooth"},
        {name:"fas fa-torah", title: "Torah"},
        {name:"fas fa-torii-gate", title: "Torii gate"},
        {name:"fas fa-tractor", title: "Tractor"},
        {name:"fas fa-trademark", title: "Trademark"},
        {name:"fas fa-traffic-light", title: "Traffic light"},
        {name:"fas fa-train", title: "Train"},
        {name:"fas fa-tram", title: "Tram"},
        {name:"fas fa-transgender", title: "Transgender"},
        {name:"fas fa-transgender-alt", title: "Transgender alt"},
        {name:"fas fa-trash", title: "Trash"},
        {name:"fas fa-trash-alt", title: "Trash alt"},
        {name:"fas fa-trash-restore", title: "Trash restore"},
        {name:"fas fa-trash-restore-alt", title: "Trash restore alt"},
        {name:"fas fa-tree", title: "Tree"},
        {name:"fas fa-trophy", title: "Trophy"},
        {name:"fas fa-truck", title: "Truck"},
        {name:"fas fa-truck-loading", title: "Truck loading"},
        {name:"fas fa-truck-monster", title: "Truck monster"},
        {name:"fas fa-truck-moving", title: "Truck moving"},
        {name:"fas fa-truck-pickup", title: "Truck pickup"},
        {name:"fas fa-tshirt", title: "Tshirt"},
        {name:"fas fa-tty", title: "Tty"},
        {name:"fas fa-tv", title: "Tv"},
        {name:"fas fa-umbrella", title: "Umbrella"},
        {name:"fas fa-umbrella-beach", title: "Umbrella beach"},
        {name:"fas fa-underline", title: "Underline"},
        {name:"fas fa-undo", title: "Undo"},
        {name:"fas fa-undo-alt", title: "Undo alt"},
        {name:"fas fa-universal-access", title: "Universal access"},
        {name:"fas fa-university", title: "University"},
        {name:"fas fa-unlink", title: "Unlink"},
        {name:"fas fa-unlock", title: "Unlock"},
        {name:"fas fa-unlock-alt", title: "Unlock alt"},
        {name:"fas fa-upload", title: "Upload"},
        {name:"fas fa-user", title: "User"},
        {name:"fas fa-user-alt", title: "User alt"},
        {name:"fas fa-user-alt-slash", title: "User alt slash"},
        {name:"fas fa-user-astronaut", title: "User astronaut"},
        {name:"fas fa-user-check", title: "User check"},
        {name:"fas fa-user-circle", title: "User circle"},
        {name:"fas fa-user-clock", title: "User clock"},
        {name:"fas fa-user-cog", title: "User cog"},
        {name:"fas fa-user-edit", title: "User edit"},
        {name:"fas fa-user-friends", title: "User friends"},
        {name:"fas fa-user-graduate", title: "User graduate"},
        {name:"fas fa-user-injured", title: "User injured"},
        {name:"fas fa-user-lock", title: "User lock"},
        {name:"fas fa-user-md", title: "User md"},
        {name:"fas fa-user-minus", title: "User minus"},
        {name:"fas fa-user-ninja", title: "User ninja"},
        {name:"fas fa-user-nurse", title: "User nurse"},
        {name:"fas fa-user-plus", title: "User plus"},
        {name:"fas fa-user-secret", title: "User secret"},
        {name:"fas fa-user-shield", title: "User shield"},
        {name:"fas fa-user-slash", title: "User slash"},
        {name:"fas fa-user-tag", title: "User tag"},
        {name:"fas fa-user-tie", title: "User tie"},
        {name:"fas fa-user-times", title: "User times"},
        {name:"fas fa-users", title: "Users"},
        {name:"fas fa-users-cog", title: "Users cog"},
        {name:"fas fa-utensil-spoon", title: "Utensil spoon"},
        {name:"fas fa-utensils", title: "Utensils"},
        {name:"fas fa-vector-square", title: "Vector square"},
        {name:"fas fa-venus", title: "Venus"},
        {name:"fas fa-venus-double", title: "Venus double"},
        {name:"fas fa-venus-mars", title: "Venus mars"},
        {name:"fas fa-vial", title: "Vial"},
        {name:"fas fa-vials", title: "Vials"},
        {name:"fas fa-video", title: "Video"},
        {name:"fas fa-video-slash", title: "Video slash"},
        {name:"fas fa-vihara", title: "Vihara"},
        {name:"fas fa-voicemail", title: "Voicemail"},
        {name:"fas fa-volleyball-ball", title: "Volleyball ball"},
        {name:"fas fa-volume-down", title: "Volume down"},
        {name:"fas fa-volume-mute", title: "Volume mute"},
        {name:"fas fa-volume-off", title: "Volume off"},
        {name:"fas fa-volume-up", title: "Volume up"},
        {name:"fas fa-vote-yea", title: "Vote yea"},
        {name:"fas fa-vr-cardboard", title: "Vr cardboard"},
        {name:"fas fa-walking", title: "Walking"},
        {name:"fas fa-wallet", title: "Wallet"},
        {name:"fas fa-warehouse", title: "Warehouse"},
        {name:"fas fa-water", title: "Water"},
        {name:"fas fa-wave-square", title: "Wave square"},
        {name:"fas fa-weight", title: "Weight"},
        {name:"fas fa-weight-hanging", title: "Weight hanging"},
        {name:"fas fa-wheelchair", title: "Wheelchair"},
        {name:"fas fa-wifi", title: "Wifi"},
        {name:"fas fa-wind", title: "Wind"},
        {name:"fas fa-window-close", title: "Window close"},
        {name:"fas fa-window-maximize", title: "Window maximize"},
        {name:"fas fa-window-minimize", title: "Window minimize"},
        {name:"fas fa-window-restore", title: "Window restore"},
        {name:"fas fa-wine-bottle", title: "Wine bottle"},
        {name:"fas fa-wine-glass", title: "Wine glass"},
        {name:"fas fa-wine-glass-alt", title: "Wine glass alt"},
        {name:"fas fa-won-sign", title: "Won sign"},
        {name:"fas fa-wrench", title: "Wrench"},
        {name:"fas fa-x-ray", title: "X ray"},
        {name:"fas fa-yen-sign", title: "Yen sign"},
        {name:"fas fa-yin-yang", title: "Yin yang"},
        {name:"far fa-ad", title: "Ad"},
        {name:"far fa-address-book", title: "Address book"},
        {name:"far fa-address-card", title: "Address card"},
        {name:"far fa-adjust", title: "Adjust"},
        {name:"far fa-air-freshener", title: "Air freshener"},
        {name:"far fa-align-center", title: "Align center"},
        {name:"far fa-align-justify", title: "Align justify"},
        {name:"far fa-align-left", title: "Align left"},
        {name:"far fa-align-right", title: "Align right"},
        {name:"far fa-allergies", title: "Allergies"},
        {name:"far fa-ambulance", title: "Ambulance"},
        {name:"far fa-american-sign-language-interpreting", title: "American sign language interpreting"},
        {name:"far fa-anchor", title: "Anchor"},
        {name:"far fa-angle-double-down", title: "Angle double down"},
        {name:"far fa-angle-double-left", title: "Angle double left"},
        {name:"far fa-angle-double-right", title: "Angle double right"},
        {name:"far fa-angle-double-up", title: "Angle double up"},
        {name:"far fa-angle-down", title: "Angle down"},
        {name:"far fa-angle-left", title: "Angle left"},
        {name:"far fa-angle-right", title: "Angle right"},
        {name:"far fa-angle-up", title: "Angle up"},
        {name:"far fa-angry", title: "Angry"},
        {name:"far fa-ankh", title: "Ankh"},
        {name:"far fa-apple-alt", title: "Apple alt"},
        {name:"far fa-archive", title: "Archive"},
        {name:"far fa-archway", title: "Archway"},
        {name:"far fa-arrow-alt-circle-down", title: "Arrow alt circle down"},
        {name:"far fa-arrow-alt-circle-left", title: "Arrow alt circle left"},
        {name:"far fa-arrow-alt-circle-right", title: "Arrow alt circle right"},
        {name:"far fa-arrow-alt-circle-up", title: "Arrow alt circle up"},
        {name:"far fa-arrow-circle-down", title: "Arrow circle down"},
        {name:"far fa-arrow-circle-left", title: "Arrow circle left"},
        {name:"far fa-arrow-circle-right", title: "Arrow circle right"},
        {name:"far fa-arrow-circle-up", title: "Arrow circle up"},
        {name:"far fa-arrow-down", title: "Arrow down"},
        {name:"far fa-arrow-left", title: "Arrow left"},
        {name:"far fa-arrow-right", title: "Arrow right"},
        {name:"far fa-arrow-up", title: "Arrow up"},
        {name:"far fa-arrows-alt", title: "Arrows alt"},
        {name:"far fa-arrows-alt-h", title: "Arrows alt h"},
        {name:"far fa-arrows-alt-v", title: "Arrows alt v"},
        {name:"far fa-assistive-listening-systems", title: "Assistive listening systems"},
        {name:"far fa-asterisk", title: "Asterisk"},
        {name:"far fa-at", title: "At"},
        {name:"far fa-atlas", title: "Atlas"},
        {name:"far fa-atom", title: "Atom"},
        {name:"far fa-audio-description", title: "Audio description"},
        {name:"far fa-award", title: "Award"},
        {name:"far fa-baby", title: "Baby"},
        {name:"far fa-baby-carriage", title: "Baby carriage"},
        {name:"far fa-backspace", title: "Backspace"},
        {name:"far fa-backward", title: "Backward"},
        {name:"far fa-bacon", title: "Bacon"},
        {name:"far fa-balance-scale", title: "Balance scale"},
        {name:"far fa-balance-scale-left", title: "Balance scale left"},
        {name:"far fa-balance-scale-right", title: "Balance scale right"},
        {name:"far fa-ban", title: "Ban"},
        {name:"far fa-band-aid", title: "Band aid"},
        {name:"far fa-barcode", title: "Barcode"},
        {name:"far fa-bars", title: "Bars"},
        {name:"far fa-baseball-ball", title: "Baseball ball"},
        {name:"far fa-basketball-ball", title: "Basketball ball"},
        {name:"far fa-bath", title: "Bath"},
        {name:"far fa-battery-empty", title: "Battery empty"},
        {name:"far fa-battery-full", title: "Battery full"},
        {name:"far fa-battery-half", title: "Battery half"},
        {name:"far fa-battery-quarter", title: "Battery quarter"},
        {name:"far fa-battery-three-quarters", title: "Battery three quarters"},
        {name:"far fa-bed", title: "Bed"},
        {name:"far fa-beer", title: "Beer"},
        {name:"far fa-bell", title: "Bell"},
        {name:"far fa-bell-slash", title: "Bell slash"},
        {name:"far fa-bezier-curve", title: "Bezier curve"},
        {name:"far fa-bible", title: "Bible"},
        {name:"far fa-bicycle", title: "Bicycle"},
        {name:"far fa-biking", title: "Biking"},
        {name:"far fa-binoculars", title: "Binoculars"},
        {name:"far fa-biohazard", title: "Biohazard"},
        {name:"far fa-birthday-cake", title: "Birthday cake"},
        {name:"far fa-blender", title: "Blender"},
        {name:"far fa-blender-phone", title: "Blender phone"},
        {name:"far fa-blind", title: "Blind"},
        {name:"far fa-blog", title: "Blog"},
        {name:"far fa-bold", title: "Bold"},
        {name:"far fa-bolt", title: "Bolt"},
        {name:"far fa-bomb", title: "Bomb"},
        {name:"far fa-bone", title: "Bone"},
        {name:"far fa-bong", title: "Bong"},
        {name:"far fa-book", title: "Book"},
        {name:"far fa-book-dead", title: "Book dead"},
        {name:"far fa-book-medical", title: "Book medical"},
        {name:"far fa-book-open", title: "Book open"},
        {name:"far fa-book-reader", title: "Book reader"},
        {name:"far fa-bookmark", title: "Bookmark"},
        {name:"far fa-border-all", title: "Border all"},
        {name:"far fa-border-none", title: "Border none"},
        {name:"far fa-border-style", title: "Border style"},
        {name:"far fa-bowling-ball", title: "Bowling ball"},
        {name:"far fa-box", title: "Box"},
        {name:"far fa-box-open", title: "Box open"},
        {name:"far fa-boxes", title: "Boxes"},
        {name:"far fa-braille", title: "Braille"},
        {name:"far fa-brain", title: "Brain"},
        {name:"far fa-bread-slice", title: "Bread slice"},
        {name:"far fa-briefcase", title: "Briefcase"},
        {name:"far fa-briefcase-medical", title: "Briefcase medical"},
        {name:"far fa-broadcast-tower", title: "Broadcast tower"},
        {name:"far fa-broom", title: "Broom"},
        {name:"far fa-brush", title: "Brush"},
        {name:"far fa-bug", title: "Bug"},
        {name:"far fa-building", title: "Building"},
        {name:"far fa-bullhorn", title: "Bullhorn"},
        {name:"far fa-bullseye", title: "Bullseye"},
        {name:"far fa-burn", title: "Burn"},
        {name:"far fa-bus", title: "Bus"},
        {name:"far fa-bus-alt", title: "Bus alt"},
        {name:"far fa-business-time", title: "Business time"},
        {name:"far fa-calculator", title: "Calculator"},
        {name:"far fa-calendar", title: "Calendar"},
        {name:"far fa-calendar-alt", title: "Calendar alt"},
        {name:"far fa-calendar-check", title: "Calendar check"},
        {name:"far fa-calendar-day", title: "Calendar day"},
        {name:"far fa-calendar-minus", title: "Calendar minus"},
        {name:"far fa-calendar-plus", title: "Calendar plus"},
        {name:"far fa-calendar-times", title: "Calendar times"},
        {name:"far fa-calendar-week", title: "Calendar week"},
        {name:"far fa-camera", title: "Camera"},
        {name:"far fa-camera-retro", title: "Camera retro"},
        {name:"far fa-campground", title: "Campground"},
        {name:"far fa-candy-cane", title: "Candy cane"},
        {name:"far fa-cannabis", title: "Cannabis"},
        {name:"far fa-capsules", title: "Capsules"},
        {name:"far fa-car", title: "Car"},
        {name:"far fa-car-alt", title: "Car alt"},
        {name:"far fa-car-battery", title: "Car battery"},
        {name:"far fa-car-crash", title: "Car crash"},
        {name:"far fa-car-side", title: "Car side"},
        {name:"far fa-caret-down", title: "Caret down"},
        {name:"far fa-caret-left", title: "Caret left"},
        {name:"far fa-caret-right", title: "Caret right"},
        {name:"far fa-caret-square-down", title: "Caret square down"},
        {name:"far fa-caret-square-left", title: "Caret square left"},
        {name:"far fa-caret-square-right", title: "Caret square right"},
        {name:"far fa-caret-square-up", title: "Caret square up"},
        {name:"far fa-caret-up", title: "Caret up"},
        {name:"far fa-carrot", title: "Carrot"},
        {name:"far fa-cart-arrow-down", title: "Cart arrow down"},
        {name:"far fa-cart-plus", title: "Cart plus"},
        {name:"far fa-cash-register", title: "Cash register"},
        {name:"far fa-cat", title: "Cat"},
        {name:"far fa-certificate", title: "Certificate"},
        {name:"far fa-chair", title: "Chair"},
        {name:"far fa-chalkboard", title: "Chalkboard"},
        {name:"far fa-chalkboard-teacher", title: "Chalkboard teacher"},
        {name:"far fa-charging-station", title: "Charging station"},
        {name:"far fa-chart-area", title: "Chart area"},
        {name:"far fa-chart-bar", title: "Chart bar"},
        {name:"far fa-chart-line", title: "Chart line"},
        {name:"far fa-chart-pie", title: "Chart pie"},
        {name:"far fa-check", title: "Check"},
        {name:"far fa-check-circle", title: "Check circle"},
        {name:"far fa-check-double", title: "Check double"},
        {name:"far fa-check-square", title: "Check square"},
        {name:"far fa-cheese", title: "Cheese"},
        {name:"far fa-chess", title: "Chess"},
        {name:"far fa-chess-bishop", title: "Chess bishop"},
        {name:"far fa-chess-board", title: "Chess board"},
        {name:"far fa-chess-king", title: "Chess king"},
        {name:"far fa-chess-knight", title: "Chess knight"},
        {name:"far fa-chess-pawn", title: "Chess pawn"},
        {name:"far fa-chess-queen", title: "Chess queen"},
        {name:"far fa-chess-rook", title: "Chess rook"},
        {name:"far fa-chevron-circle-down", title: "Chevron circle down"},
        {name:"far fa-chevron-circle-left", title: "Chevron circle left"},
        {name:"far fa-chevron-circle-right", title: "Chevron circle right"},
        {name:"far fa-chevron-circle-up", title: "Chevron circle up"},
        {name:"far fa-chevron-down", title: "Chevron down"},
        {name:"far fa-chevron-left", title: "Chevron left"},
        {name:"far fa-chevron-right", title: "Chevron right"},
        {name:"far fa-chevron-up", title: "Chevron up"},
        {name:"far fa-child", title: "Child"},
        {name:"far fa-church", title: "Church"},
        {name:"far fa-circle", title: "Circle"},
        {name:"far fa-circle-notch", title: "Circle notch"},
        {name:"far fa-city", title: "City"},
        {name:"far fa-clinic-medical", title: "Clinic medical"},
        {name:"far fa-clipboard", title: "Clipboard"},
        {name:"far fa-clipboard-check", title: "Clipboard check"},
        {name:"far fa-clipboard-list", title: "Clipboard list"},
        {name:"far fa-clock", title: "Clock"},
        {name:"far fa-clone", title: "Clone"},
        {name:"far fa-closed-captioning", title: "Closed captioning"},
        {name:"far fa-cloud", title: "Cloud"},
        {name:"far fa-cloud-download-alt", title: "Cloud download alt"},
        {name:"far fa-cloud-meatball", title: "Cloud meatball"},
        {name:"far fa-cloud-moon", title: "Cloud moon"},
        {name:"far fa-cloud-moon-rain", title: "Cloud moon rain"},
        {name:"far fa-cloud-rain", title: "Cloud rain"},
        {name:"far fa-cloud-showers-heavy", title: "Cloud showers heavy"},
        {name:"far fa-cloud-sun", title: "Cloud sun"},
        {name:"far fa-cloud-sun-rain", title: "Cloud sun rain"},
        {name:"far fa-cloud-upload-alt", title: "Cloud upload alt"},
        {name:"far fa-cocktail", title: "Cocktail"},
        {name:"far fa-code", title: "Code"},
        {name:"far fa-code-branch", title: "Code branch"},
        {name:"far fa-coffee", title: "Coffee"},
        {name:"far fa-cog", title: "Cog"},
        {name:"far fa-cogs", title: "Cogs"},
        {name:"far fa-coins", title: "Coins"},
        {name:"far fa-columns", title: "Columns"},
        {name:"far fa-comment", title: "Comment"},
        {name:"far fa-comment-alt", title: "Comment alt"},
        {name:"far fa-comment-dollar", title: "Comment dollar"},
        {name:"far fa-comment-dots", title: "Comment dots"},
        {name:"far fa-comment-medical", title: "Comment medical"},
        {name:"far fa-comment-slash", title: "Comment slash"},
        {name:"far fa-comments", title: "Comments"},
        {name:"far fa-comments-dollar", title: "Comments dollar"},
        {name:"far fa-compact-disc", title: "Compact disc"},
        {name:"far fa-compass", title: "Compass"},
        {name:"far fa-compress", title: "Compress"},
        {name:"far fa-compress-arrows-alt", title: "Compress arrows alt"},
        {name:"far fa-concierge-bell", title: "Concierge bell"},
        {name:"far fa-cookie", title: "Cookie"},
        {name:"far fa-cookie-bite", title: "Cookie bite"},
        {name:"far fa-copy", title: "Copy"},
        {name:"far fa-copyright", title: "Copyright"},
        {name:"far fa-couch", title: "Couch"},
        {name:"far fa-credit-card", title: "Credit card"},
        {name:"far fa-crop", title: "Crop"},
        {name:"far fa-crop-alt", title: "Crop alt"},
        {name:"far fa-cross", title: "Cross"},
        {name:"far fa-crosshairs", title: "Crosshairs"},
        {name:"far fa-crow", title: "Crow"},
        {name:"far fa-crown", title: "Crown"},
        {name:"far fa-crutch", title: "Crutch"},
        {name:"far fa-cube", title: "Cube"},
        {name:"far fa-cubes", title: "Cubes"},
        {name:"far fa-cut", title: "Cut"},
        {name:"far fa-database", title: "Database"},
        {name:"far fa-deaf", title: "Deaf"},
        {name:"far fa-democrat", title: "Democrat"},
        {name:"far fa-desktop", title: "Desktop"},
        {name:"far fa-dharmachakra", title: "Dharmachakra"},
        {name:"far fa-diagnoses", title: "Diagnoses"},
        {name:"far fa-dice", title: "Dice"},
        {name:"far fa-dice-d20", title: "Dice d20"},
        {name:"far fa-dice-d6", title: "Dice d6"},
        {name:"far fa-dice-five", title: "Dice five"},
        {name:"far fa-dice-four", title: "Dice four"},
        {name:"far fa-dice-one", title: "Dice one"},
        {name:"far fa-dice-six", title: "Dice six"},
        {name:"far fa-dice-three", title: "Dice three"},
        {name:"far fa-dice-two", title: "Dice two"},
        {name:"far fa-digital-tachograph", title: "Digital tachograph"},
        {name:"far fa-directions", title: "Directions"},
        {name:"far fa-divide", title: "Divide"},
        {name:"far fa-dizzy", title: "Dizzy"},
        {name:"far fa-dna", title: "Dna"},
        {name:"far fa-dog", title: "Dog"},
        {name:"far fa-dollar-sign", title: "Dollar sign"},
        {name:"far fa-dolly", title: "Dolly"},
        {name:"far fa-dolly-flatbed", title: "Dolly flatbed"},
        {name:"far fa-donate", title: "Donate"},
        {name:"far fa-door-closed", title: "Door closed"},
        {name:"far fa-door-open", title: "Door open"},
        {name:"far fa-dot-circle", title: "Dot circle"},
        {name:"far fa-dove", title: "Dove"},
        {name:"far fa-download", title: "Download"},
        {name:"far fa-drafting-compass", title: "Drafting compass"},
        {name:"far fa-dragon", title: "Dragon"},
        {name:"far fa-draw-polygon", title: "Draw polygon"},
        {name:"far fa-drum", title: "Drum"},
        {name:"far fa-drum-steelpan", title: "Drum steelpan"},
        {name:"far fa-drumstick-bite", title: "Drumstick bite"},
        {name:"far fa-dumbbell", title: "Dumbbell"},
        {name:"far fa-dumpster", title: "Dumpster"},
        {name:"far fa-dumpster-fire", title: "Dumpster fire"},
        {name:"far fa-dungeon", title: "Dungeon"},
        {name:"far fa-edit", title: "Edit"},
        {name:"far fa-egg", title: "Egg"},
        {name:"far fa-eject", title: "Eject"},
        {name:"far fa-ellipsis-h", title: "Ellipsis h"},
        {name:"far fa-ellipsis-v", title: "Ellipsis v"},
        {name:"far fa-envelope", title: "Envelope"},
        {name:"far fa-envelope-open", title: "Envelope open"},
        {name:"far fa-envelope-open-text", title: "Envelope open text"},
        {name:"far fa-envelope-square", title: "Envelope square"},
        {name:"far fa-equals", title: "Equals"},
        {name:"far fa-eraser", title: "Eraser"},
        {name:"far fa-ethernet", title: "Ethernet"},
        {name:"far fa-euro-sign", title: "Euro sign"},
        {name:"far fa-exchange-alt", title: "Exchange alt"},
        {name:"far fa-exclamation", title: "Exclamation"},
        {name:"far fa-exclamation-circle", title: "Exclamation circle"},
        {name:"far fa-exclamation-triangle", title: "Exclamation triangle"},
        {name:"far fa-expand", title: "Expand"},
        {name:"far fa-expand-arrows-alt", title: "Expand arrows alt"},
        {name:"far fa-external-link-alt", title: "External link alt"},
        {name:"far fa-external-link-square-alt", title: "External link square alt"},
        {name:"far fa-eye", title: "Eye"},
        {name:"far fa-eye-dropper", title: "Eye dropper"},
        {name:"far fa-eye-slash", title: "Eye slash"},
        {name:"far fa-fan", title: "Fan"},
        {name:"far fa-fast-backward", title: "Fast backward"},
        {name:"far fa-fast-forward", title: "Fast forward"},
        {name:"far fa-fax", title: "Fax"},
        {name:"far fa-feather", title: "Feather"},
        {name:"far fa-feather-alt", title: "Feather alt"},
        {name:"far fa-female", title: "Female"},
        {name:"far fa-fighter-jet", title: "Fighter jet"},
        {name:"far fa-file", title: "File"},
        {name:"far fa-file-alt", title: "File alt"},
        {name:"far fa-file-archive", title: "File archive"},
        {name:"far fa-file-audio", title: "File audio"},
        {name:"far fa-file-code", title: "File code"},
        {name:"far fa-file-contract", title: "File contract"},
        {name:"far fa-file-csv", title: "File csv"},
        {name:"far fa-file-download", title: "File download"},
        {name:"far fa-file-excel", title: "File excel"},
        {name:"far fa-file-export", title: "File export"},
        {name:"far fa-file-image", title: "File image"},
        {name:"far fa-file-import", title: "File import"},
        {name:"far fa-file-invoice", title: "File invoice"},
        {name:"far fa-file-invoice-dollar", title: "File invoice dollar"},
        {name:"far fa-file-medical", title: "File medical"},
        {name:"far fa-file-medical-alt", title: "File medical alt"},
        {name:"far fa-file-pdf", title: "File pdf"},
        {name:"far fa-file-powerpoint", title: "File powerpoint"},
        {name:"far fa-file-prescription", title: "File prescription"},
        {name:"far fa-file-signature", title: "File signature"},
        {name:"far fa-file-upload", title: "File upload"},
        {name:"far fa-file-video", title: "File video"},
        {name:"far fa-file-word", title: "File word"},
        {name:"far fa-fill", title: "Fill"},
        {name:"far fa-fill-drip", title: "Fill drip"},
        {name:"far fa-film", title: "Film"},
        {name:"far fa-filter", title: "Filter"},
        {name:"far fa-fingerprint", title: "Fingerprint"},
        {name:"far fa-fire", title: "Fire"},
        {name:"far fa-fire-alt", title: "Fire alt"},
        {name:"far fa-fire-extinguisher", title: "Fire extinguisher"},
        {name:"far fa-first-aid", title: "First aid"},
        {name:"far fa-fish", title: "Fish"},
        {name:"far fa-fist-raised", title: "Fist raised"},
        {name:"far fa-flag", title: "Flag"},
        {name:"far fa-flag-checkered", title: "Flag checkered"},
        {name:"far fa-flag-usa", title: "Flag usa"},
        {name:"far fa-flask", title: "Flask"},
        {name:"far fa-flushed", title: "Flushed"},
        {name:"far fa-folder", title: "Folder"},
        {name:"far fa-folder-minus", title: "Folder minus"},
        {name:"far fa-folder-open", title: "Folder open"},
        {name:"far fa-folder-plus", title: "Folder plus"},
        {name:"far fa-font", title: "Font"},
        {name:"far fa-football-ball", title: "Football ball"},
        {name:"far fa-forward", title: "Forward"},
        {name:"far fa-frog", title: "Frog"},
        {name:"far fa-frown", title: "Frown"},
        {name:"far fa-frown-open", title: "Frown open"},
        {name:"far fa-funnel-dollar", title: "Funnel dollar"},
        {name:"far fa-futbol", title: "Futbol"},
        {name:"far fa-gamepad", title: "Gamepad"},
        {name:"far fa-gas-pump", title: "Gas pump"},
        {name:"far fa-gavel", title: "Gavel"},
        {name:"far fa-gem", title: "Gem"},
        {name:"far fa-genderless", title: "Genderless"},
        {name:"far fa-ghost", title: "Ghost"},
        {name:"far fa-gift", title: "Gift"},
        {name:"far fa-gifts", title: "Gifts"},
        {name:"far fa-glass-cheers", title: "Glass cheers"},
        {name:"far fa-glass-martini", title: "Glass martini"},
        {name:"far fa-glass-martini-alt", title: "Glass martini alt"},
        {name:"far fa-glass-whiskey", title: "Glass whiskey"},
        {name:"far fa-glasses", title: "Glasses"},
        {name:"far fa-globe", title: "Globe"},
        {name:"far fa-globe-africa", title: "Globe africa"},
        {name:"far fa-globe-americas", title: "Globe americas"},
        {name:"far fa-globe-asia", title: "Globe asia"},
        {name:"far fa-globe-europe", title: "Globe europe"},
        {name:"far fa-golf-ball", title: "Golf ball"},
        {name:"far fa-gopuram", title: "Gopuram"},
        {name:"far fa-graduation-cap", title: "Graduation cap"},
        {name:"far fa-greater-than", title: "Greater than"},
        {name:"far fa-greater-than-equal", title: "Greater than equal"},
        {name:"far fa-grimace", title: "Grimace"},
        {name:"far fa-grin", title: "Grin"},
        {name:"far fa-grin-alt", title: "Grin alt"},
        {name:"far fa-grin-beam", title: "Grin beam"},
        {name:"far fa-grin", title: "Grin"},
        {name:"fab fa-500px", title: "500px"},
        {name:"fab fa-accessible-icon", title: "Accessible icon"},
        {name:"fab fa-accusoft", title: "Accusoft"},
        {name:"fab fa-acquisitions-incorporated", title: "Acquisitions incorporated"},
        {name:"fab fa-adn", title: "Adn"},
        {name:"fab fa-adobe", title: "Adobe"},
        {name:"fab fa-adversal", title: "Adversal"},
        {name:"fab fa-affiliatetheme", title: "Affiliatetheme"},
        {name:"fab fa-airbnb", title: "Airbnb"},
        {name:"fab fa-algolia", title: "Algolia"},
        {name:"fab fa-alipay", title: "Alipay"},
        {name:"fab fa-amazon", title: "Amazon"},
        {name:"fab fa-amazon-pay", title: "Amazon pay"},
        {name:"fab fa-amilia", title: "Amilia"},
        {name:"fab fa-android", title: "Android"},
        {name:"fab fa-angellist", title: "Angellist"},
        {name:"fab fa-angrycreative", title: "Angrycreative"},
        {name:"fab fa-angular", title: "Angular"},
        {name:"fab fa-app-store", title: "App store"},
        {name:"fab fa-app-store-ios", title: "App store ios"},
        {name:"fab fa-apper", title: "Apper"},
        {name:"fab fa-apple", title: "Apple"},
        {name:"fab fa-apple-pay", title: "Apple pay"},
        {name:"fab fa-artstation", title: "Artstation"},
        {name:"fab fa-asymmetrik", title: "Asymmetrik"},
        {name:"fab fa-atlassian", title: "Atlassian"},
        {name:"fab fa-audible", title: "Audible"},
        {name:"fab fa-autoprefixer", title: "Autoprefixer"},
        {name:"fab fa-avianex", title: "Avianex"},
        {name:"fab fa-aviato", title: "Aviato"},
        {name:"fab fa-aws", title: "Aws"},
        {name:"fab fa-bandcamp", title: "Bandcamp"},
        {name:"fab fa-battle-net", title: "Battle net"},
        {name:"fab fa-behance", title: "Behance"},
        {name:"fab fa-behance-square", title: "Behance square"},
        {name:"fab fa-bimobject", title: "Bimobject"},
        {name:"fab fa-bitbucket", title: "Bitbucket"},
        {name:"fab fa-bitcoin", title: "Bitcoin"},
        {name:"fab fa-bity", title: "Bity"},
        {name:"fab fa-black-tie", title: "Black tie"},
        {name:"fab fa-blackberry", title: "Blackberry"},
        {name:"fab fa-blogger", title: "Blogger"},
        {name:"fab fa-blogger-b", title: "Blogger b"},
        {name:"fab fa-bluetooth", title: "Bluetooth"},
        {name:"fab fa-bluetooth-b", title: "Bluetooth b"},
        {name:"fab fa-bootstrap", title: "Bootstrap"},
        {name:"fab fa-btc", title: "Btc"},
        {name:"fab fa-buffer", title: "Buffer"},
        {name:"fab fa-buromobelexperte", title: "Buromobelexperte"},
        {name:"fab fa-buy-n-large", title: "Buy n large"},
        {name:"fab fa-buysellads", title: "Buysellads"},
        {name:"fab fa-canadian-maple-leaf", title: "Canadian maple leaf"},
        {name:"fab fa-cc-amazon-pay", title: "Cc amazon pay"},
        {name:"fab fa-cc-amex", title: "Cc amex"},
        {name:"fab fa-cc-apple-pay", title: "Cc apple pay"},
        {name:"fab fa-cc-diners-club", title: "Cc diners club"},
        {name:"fab fa-cc-discover", title: "Cc discover"},
        {name:"fab fa-cc-jcb", title: "Cc jcb"},
        {name:"fab fa-cc-mastercard", title: "Cc mastercard"},
        {name:"fab fa-cc-paypal", title: "Cc paypal"},
        {name:"fab fa-cc-stripe", title: "Cc stripe"},
        {name:"fab fa-cc-visa", title: "Cc visa"},
        {name:"fab fa-centercode", title: "Centercode"},
        {name:"fab fa-centos", title: "Centos"},
        {name:"fab fa-chrome", title: "Chrome"},
        {name:"fab fa-chromecast", title: "Chromecast"},
        {name:"fab fa-cloudscale", title: "Cloudscale"},
        {name:"fab fa-cloudsmith", title: "Cloudsmith"},
        {name:"fab fa-cloudversify", title: "Cloudversify"},
        {name:"fab fa-codepen", title: "Codepen"},
        {name:"fab fa-codiepie", title: "Codiepie"},
        {name:"fab fa-confluence", title: "Confluence"},
        {name:"fab fa-connectdevelop", title: "Connectdevelop"},
        {name:"fab fa-contao", title: "Contao"},
        {name:"fab fa-cotton-bureau", title: "Cotton bureau"},
        {name:"fab fa-cpanel", title: "Cpanel"},
        {name:"fab fa-creative-commons", title: "Creative commons"},
        {name:"fab fa-creative-commons-by", title: "Creative commons by"},
        {name:"fab fa-creative-commons-nc", title: "Creative commons nc"},
        {name:"fab fa-creative-commons-nc-eu", title: "Creative commons nc eu"},
        {name:"fab fa-creative-commons-nc-jp", title: "Creative commons nc jp"},
        {name:"fab fa-creative-commons-nd", title: "Creative commons nd"},
        {name:"fab fa-creative-commons-pd", title: "Creative commons pd"},
        {name:"fab fa-creative-commons-pd-alt", title: "Creative commons pd alt"},
        {name:"fab fa-creative-commons-remix", title: "Creative commons remix"},
        {name:"fab fa-creative-commons-sa", title: "Creative commons sa"},
        {name:"fab fa-creative-commons-sampling", title: "Creative commons sampling"},
        {name:"fab fa-creative-commons-sampling-plus", title: "Creative commons sampling plus"},
        {name:"fab fa-creative-commons-share", title: "Creative commons share"},
        {name:"fab fa-creative-commons-zero", title: "Creative commons zero"},
        {name:"fab fa-critical-role", title: "Critical role"},
        {name:"fab fa-css3", title: "Css3"},
        {name:"fab fa-css3-alt", title: "Css3 alt"},
        {name:"fab fa-cuttlefish", title: "Cuttlefish"},
        {name:"fab fa-d-and-d", title: "D and d"},
        {name:"fab fa-d-and-d-beyond", title: "D and d beyond"},
        {name:"fab fa-dashcube", title: "Dashcube"},
        {name:"fab fa-delicious", title: "Delicious"},
        {name:"fab fa-deploydog", title: "Deploydog"},
        {name:"fab fa-deskpro", title: "Deskpro"},
        {name:"fab fa-dev", title: "Dev"},
        {name:"fab fa-deviantart", title: "Deviantart"},
        {name:"fab fa-dhl", title: "Dhl"},
        {name:"fab fa-diaspora", title: "Diaspora"},
        {name:"fab fa-digg", title: "Digg"},
        {name:"fab fa-digital-ocean", title: "Digital ocean"},
        {name:"fab fa-discord", title: "Discord"},
        {name:"fab fa-discourse", title: "Discourse"},
        {name:"fab fa-dochub", title: "Dochub"},
        {name:"fab fa-docker", title: "Docker"},
        {name:"fab fa-draft2digital", title: "Draft2digital"},
        {name:"fab fa-dribbble", title: "Dribbble"},
        {name:"fab fa-dribbble-square", title: "Dribbble square"},
        {name:"fab fa-dropbox", title: "Dropbox"},
        {name:"fab fa-drupal", title: "Drupal"},
        {name:"fab fa-dyalog", title: "Dyalog"},
        {name:"fab fa-earlybirds", title: "Earlybirds"},
        {name:"fab fa-ebay", title: "Ebay"},
        {name:"fab fa-edge", title: "Edge"},
        {name:"fab fa-elementor", title: "Elementor"},
        {name:"fab fa-ello", title: "Ello"},
        {name:"fab fa-ember", title: "Ember"},
        {name:"fab fa-empire", title: "Empire"},
        {name:"fab fa-envira", title: "Envira"},
        {name:"fab fa-erlang", title: "Erlang"},
        {name:"fab fa-ethereum", title: "Ethereum"},
        {name:"fab fa-etsy", title: "Etsy"},
        {name:"fab fa-evernote", title: "Evernote"},
        {name:"fab fa-expeditedssl", title: "Expeditedssl"},
        {name:"fab fa-facebook", title: "Facebook"},
        {name:"fab fa-facebook-f", title: "Facebook f"},
        {name:"fab fa-facebook-messenger", title: "Facebook messenger"},
        {name:"fab fa-facebook-square", title: "Facebook square"},
        {name:"fab fa-fantasy-flight-games", title: "Fantasy flight games"},
        {name:"fab fa-fedex", title: "Fedex"},
        {name:"fab fa-fedora", title: "Fedora"},
        {name:"fab fa-figma", title: "Figma"},
        {name:"fab fa-firefox", title: "Firefox"},
        {name:"fab fa-first-order", title: "First order"},
        {name:"fab fa-first-order-alt", title: "First order alt"},
        {name:"fab fa-firstdraft", title: "Firstdraft"},
        {name:"fab fa-flickr", title: "Flickr"},
        {name:"fab fa-flipboard", title: "Flipboard"},
        {name:"fab fa-fly", title: "Fly"},
        {name:"fab fa-font-awesome", title: "Font awesome"},
        {name:"fab fa-font-awesome-alt", title: "Font awesome alt"},
        {name:"fab fa-font-awesome-flag", title: "Font awesome flag"},
        {name:"fab fa-fonticons", title: "Fonticons"},
        {name:"fab fa-fonticons-fi", title: "Fonticons fi"},
        {name:"fab fa-fort-awesome", title: "Fort awesome"},
        {name:"fab fa-fort-awesome-alt", title: "Fort awesome alt"},
        {name:"fab fa-forumbee", title: "Forumbee"},
        {name:"fab fa-foursquare", title: "Foursquare"},
        {name:"fab fa-free-code-camp", title: "Free code camp"},
        {name:"fab fa-freebsd", title: "Freebsd"},
        {name:"fab fa-fulcrum", title: "Fulcrum"},
        {name:"fab fa-galactic-republic", title: "Galactic republic"},
        {name:"fab fa-galactic-senate", title: "Galactic senate"},
        {name:"fab fa-get-pocket", title: "Get pocket"},
        {name:"fab fa-gg", title: "Gg"},
        {name:"fab fa-gg-circle", title: "Gg circle"},
        {name:"fab fa-git", title: "Git"},
        {name:"fab fa-git-alt", title: "Git alt"},
        {name:"fab fa-git-square", title: "Git square"},
        {name:"fab fa-github", title: "Github"},
        {name:"fab fa-github-alt", title: "Github alt"},
        {name:"fab fa-github-square", title: "Github square"},
        {name:"fab fa-gitkraken", title: "Gitkraken"},
        {name:"fab fa-gitlab", title: "Gitlab"},
        {name:"fab fa-gitter", title: "Gitter"},
        {name:"fab fa-glide", title: "Glide"},
        {name:"fab fa-glide-g", title: "Glide g"},
        {name:"fab fa-gofore", title: "Gofore"},
        {name:"fab fa-goodreads", title: "Goodreads"},
        {name:"fab fa-goodreads-g", title: "Goodreads g"},
        {name:"fab fa-google", title: "Google"},
        {name:"fab fa-google-drive", title: "Google drive"},
        {name:"fab fa-google-play", title: "Google play"},
        {name:"fab fa-google-plus", title: "Google plus"},
        {name:"fab fa-google-plus-g", title: "Google plus g"},
        {name:"fab fa-google-plus-square", title: "Google plus square"},
        {name:"fab fa-google-wallet", title: "Google wallet"},
        {name:"fab fa-gratipay", title: "Gratipay"},
        {name:"fab fa-grav", title: "Grav"},
        {name:"fab fa-gripfire", title: "Gripfire"},
        {name:"fab fa-grunt", title: "Grunt"},
        {name:"fab fa-gulp", title: "Gulp"},
        {name:"fab fa-hacker-news", title: "Hacker news"},
        {name:"fab fa-hacker-news-square", title: "Hacker news square"},
        {name:"fab fa-hackerrank", title: "Hackerrank"},
        {name:"fab fa-hips", title: "Hips"},
        {name:"fab fa-hire-a-helper", title: "Hire a helper"},
        {name:"fab fa-hooli", title: "Hooli"},
        {name:"fab fa-hornbill", title: "Hornbill"},
        {name:"fab fa-hotjar", title: "Hotjar"},
        {name:"fab fa-houzz", title: "Houzz"},
        {name:"fab fa-html5", title: "Html5"},
        {name:"fab fa-hubspot", title: "Hubspot"},
        {name:"fab fa-imdb", title: "Imdb"},
        {name:"fab fa-instagram", title: "Instagram"},
        {name:"fab fa-intercom", title: "Intercom"},
        {name:"fab fa-internet-explorer", title: "Internet explorer"},
        {name:"fab fa-invision", title: "Invision"},
        {name:"fab fa-ioxhost", title: "Ioxhost"},
        {name:"fab fa-itch-io", title: "Itch io"},
        {name:"fab fa-itunes", title: "Itunes"},
        {name:"fab fa-itunes-note", title: "Itunes note"},
        {name:"fab fa-java", title: "Java"},
        {name:"fab fa-jedi-order", title: "Jedi order"},
        {name:"fab fa-jenkins", title: "Jenkins"},
        {name:"fab fa-jira", title: "Jira"},
        {name:"fab fa-joget", title: "Joget"},
        {name:"fab fa-joomla", title: "Joomla"},
        {name:"fab fa-js", title: "Js"},
        {name:"fab fa-js-square", title: "Js square"},
        {name:"fab fa-jsfiddle", title: "Jsfiddle"},
        {name:"fab fa-kaggle", title: "Kaggle"},
        {name:"fab fa-keybase", title: "Keybase"},
        {name:"fab fa-keycdn", title: "Keycdn"},
        {name:"fab fa-kickstarter", title: "Kickstarter"},
        {name:"fab fa-kickstarter-k", title: "Kickstarter k"},
        {name:"fab fa-korvue", title: "Korvue"},
        {name:"fab fa-laravel", title: "Laravel"},
        {name:"fab fa-lastfm", title: "Lastfm"},
        {name:"fab fa-lastfm-square", title: "Lastfm square"},
        {name:"fab fa-leanpub", title: "Leanpub"},
        {name:"fab fa-less", title: "Less"},
        {name:"fab fa-line", title: "Line"},
        {name:"fab fa-linkedin", title: "Linkedin"},
        {name:"fab fa-linkedin-in", title: "Linkedin in"},
        {name:"fab fa-linode", title: "Linode"},
        {name:"fab fa-linux", title: "Linux"},
        {name:"fab fa-lyft", title: "Lyft"},
        {name:"fab fa-magento", title: "Magento"},
        {name:"fab fa-mailchimp", title: "Mailchimp"},
        {name:"fab fa-mandalorian", title: "Mandalorian"},
        {name:"fab fa-markdown", title: "Markdown"},
        {name:"fab fa-mastodon", title: "Mastodon"},
        {name:"fab fa-maxcdn", title: "Maxcdn"},
        {name:"fab fa-mdb", title: "Mdb"},
        {name:"fab fa-medapps", title: "Medapps"},
        {name:"fab fa-medium", title: "Medium"},
        {name:"fab fa-medium-m", title: "Medium m"},
        {name:"fab fa-medrt", title: "Medrt"},
        {name:"fab fa-meetup", title: "Meetup"},
        {name:"fab fa-megaport", title: "Megaport"},
        {name:"fab fa-mendeley", title: "Mendeley"},
        {name:"fab fa-microsoft", title: "Microsoft"},
        {name:"fab fa-mix", title: "Mix"},
        {name:"fab fa-mixcloud", title: "Mixcloud"},
        {name:"fab fa-mizuni", title: "Mizuni"},
        {name:"fab fa-modx", title: "Modx"},
        {name:"fab fa-monero", title: "Monero"},
        {name:"fab fa-napster", title: "Napster"},
        {name:"fab fa-neos", title: "Neos"},
        {name:"fab fa-nimblr", title: "Nimblr"},
        {name:"fab fa-node", title: "Node"},
        {name:"fab fa-node-js", title: "Node js"},
        {name:"fab fa-npm", title: "Npm"},
        {name:"fab fa-ns8", title: "Ns8"},
        {name:"fab fa-nutritionix", title: "Nutritionix"},
        {name:"fab fa-odnoklassniki", title: "Odnoklassniki"},
        {name:"fab fa-odnoklassniki-square", title: "Odnoklassniki square"},
        {name:"fab fa-old-republic", title: "Old republic"},
        {name:"fab fa-opencart", title: "Opencart"},
        {name:"fab fa-openid", title: "Openid"},
        {name:"fab fa-opera", title: "Opera"},
        {name:"fab fa-optin-monster", title: "Optin monster"},
        {name:"fab fa-orcid", title: "Orcid"},
        {name:"fab fa-osi", title: "Osi"},
        {name:"fab fa-page4", title: "Page4"},
        {name:"fab fa-pagelines", title: "Pagelines"},
        {name:"fab fa-palfed", title: "Palfed"},
        {name:"fab fa-patreon", title: "Patreon"},
        {name:"fab fa-paypal", title: "Paypal"},
        {name:"fab fa-penny-arcade", title: "Penny arcade"},
        {name:"fab fa-periscope", title: "Periscope"},
        {name:"fab fa-phabricator", title: "Phabricator"},
        {name:"fab fa-phoenix-framework", title: "Phoenix framework"},
        {name:"fab fa-phoenix-squadron", title: "Phoenix squadron"},
        {name:"fab fa-php", title: "Php"},
        {name:"fab fa-pied-piper", title: "Pied piper"},
        {name:"fab fa-pied-piper-alt", title: "Pied piper alt"},
        {name:"fab fa-pied-piper-hat", title: "Pied piper hat"},
        {name:"fab fa-pied-piper-pp", title: "Pied piper pp"},
        {name:"fab fa-pinterest", title: "Pinterest"},
        {name:"fab fa-pinterest-p", title: "Pinterest p"},
        {name:"fab fa-pinterest-square", title: "Pinterest square"},
        {name:"fab fa-playstation", title: "Playstation"},
        {name:"fab fa-product-hunt", title: "Product hunt"},
        {name:"fab fa-pushed", title: "Pushed"},
        {name:"fab fa-python", title: "Python"},
        {name:"fab fa-qq", title: "Qq"},
        {name:"fab fa-quinscape", title: "Quinscape"},
        {name:"fab fa-quora", title: "Quora"},
        {name:"fab fa-r-project", title: "R project"},
        {name:"fab fa-raspberry-pi", title: "Raspberry pi"},
        {name:"fab fa-ravelry", title: "Ravelry"},
        {name:"fab fa-react", title: "React"},
        {name:"fab fa-reacteurope", title: "Reacteurope"},
        {name:"fab fa-readme", title: "Readme"},
        {name:"fab fa-rebel", title: "Rebel"},
        {name:"fab fa-red-river", title: "Red river"},
        {name:"fab fa-reddit", title: "Reddit"},
        {name:"fab fa-reddit-alien", title: "Reddit alien"},
        {name:"fab fa-reddit-square", title: "Reddit square"},
        {name:"fab fa-redhat", title: "Redhat"},
        {name:"fab fa-renren", title: "Renren"},
        {name:"fab fa-replyd", title: "Replyd"},
        {name:"fab fa-researchgate", title: "Researchgate"},
        {name:"fab fa-resolving", title: "Resolving"},
        {name:"fab fa-rev", title: "Rev"},
        {name:"fab fa-rocketchat", title: "Rocketchat"},
        {name:"fab fa-rockrms", title: "Rockrms"},
        {name:"fab fa-safari", title: "Safari"},
        {name:"fab fa-salesforce", title: "Salesforce"},
        {name:"fab fa-sass", title: "Sass"},
        {name:"fab fa-schlix", title: "Schlix"},
        {name:"fab fa-scribd", title: "Scribd"},
        {name:"fab fa-searchengin", title: "Searchengin"},
        {name:"fab fa-sellcast", title: "Sellcast"},
        {name:"fab fa-sellsy", title: "Sellsy"},
        {name:"fab fa-servicestack", title: "Servicestack"},
        {name:"fab fa-shirtsinbulk", title: "Shirtsinbulk"},
        {name:"fab fa-shopware", title: "Shopware"},
        {name:"fab fa-simplybuilt", title: "Simplybuilt"},
        {name:"fab fa-sistrix", title: "Sistrix"},
        {name:"fab fa-sith", title: "Sith"},
        {name:"fab fa-sketch", title: "Sketch"},
        {name:"fab fa-skyatlas", title: "Skyatlas"},
        {name:"fab fa-skype", title: "Skype"},
        {name:"fab fa-slack", title: "Slack"},
        {name:"fab fa-slack-hash", title: "Slack hash"},
        {name:"fab fa-slideshare", title: "Slideshare"},
        {name:"fab fa-snapchat", title: "Snapchat"},
        {name:"fab fa-snapchat-ghost", title: "Snapchat ghost"},
        {name:"fab fa-snapchat-square", title: "Snapchat square"},
        {name:"fab fa-soundcloud", title: "Soundcloud"},
        {name:"fab fa-sourcetree", title: "Sourcetree"},
        {name:"fab fa-speakap", title: "Speakap"},
        {name:"fab fa-speaker-deck", title: "Speaker deck"},
        {name:"fab fa-spotify", title: "Spotify"},
        {name:"fab fa-squarespace", title: "Squarespace"},
        {name:"fab fa-stack-exchange", title: "Stack exchange"},
        {name:"fab fa-stack-overflow", title: "Stack overflow"},
        {name:"fab fa-stackpath", title: "Stackpath"},
        {name:"fab fa-staylinked", title: "Staylinked"},
        {name:"fab fa-steam", title: "Steam"},
        {name:"fab fa-steam-square", title: "Steam square"},
        {name:"fab fa-steam-symbol", title: "Steam symbol"},
        {name:"fab fa-sticker-mule", title: "Sticker mule"},
        {name:"fab fa-strava", title: "Strava"},
        {name:"fab fa-stripe", title: "Stripe"},
        {name:"fab fa-stripe-s", title: "Stripe s"},
        {name:"fab fa-studiovinari", title: "Studiovinari"},
        {name:"fab fa-stumbleupon", title: "Stumbleupon"},
        {name:"fab fa-stumbleupon-circle", title: "Stumbleupon circle"},
        {name:"fab fa-superpowers", title: "Superpowers"},
        {name:"fab fa-supple", title: "Supple"},
        {name:"fab fa-suse", title: "Suse"},
        {name:"fab fa-swift", title: "Swift"},
        {name:"fab fa-symfony", title: "Symfony"},
        {name:"fab fa-teamspeak", title: "Teamspeak"},
        {name:"fab fa-telegram", title: "Telegram"},
        {name:"fab fa-telegram-plane", title: "Telegram plane"},
        {name:"fab fa-tencent-weibo", title: "Tencent weibo"},
        {name:"fab fa-the-red-yeti", title: "The red yeti"},
        {name:"fab fa-themeco", title: "Themeco"},
        {name:"fab fa-themeisle", title: "Themeisle"},
        {name:"fab fa-think-peaks", title: "Think peaks"},
        {name:"fab fa-trade-federation", title: "Trade federation"},
        {name:"fab fa-trello", title: "Trello"},
        {name:"fab fa-tripadvisor", title: "Tripadvisor"},
        {name:"fab fa-tumblr", title: "Tumblr"},
        {name:"fab fa-tumblr-square", title: "Tumblr square"},
        {name:"fab fa-twitch", title: "Twitch"},
        {name:"fab fa-twitter", title: "Twitter"},
        {name:"fab fa-twitter-square", title: "Twitter square"},
        {name:"fab fa-typo3", title: "Typo3"},
        {name:"fab fa-uber", title: "Uber"},
        {name:"fab fa-ubuntu", title: "Ubuntu"},
        {name:"fab fa-uikit", title: "Uikit"},
        {name:"fab fa-umbraco", title: "Umbraco"},
        {name:"fab fa-uniregistry", title: "Uniregistry"},
        {name:"fab fa-untappd", title: "Untappd"},
        {name:"fab fa-ups", title: "Ups"},
        {name:"fab fa-usb", title: "Usb"},
        {name:"fab fa-usps", title: "Usps"},
        {name:"fab fa-ussunnah", title: "Ussunnah"},
        {name:"fab fa-vaadin", title: "Vaadin"},
        {name:"fab fa-viacoin", title: "Viacoin"},
        {name:"fab fa-viadeo", title: "Viadeo"},
        {name:"fab fa-viadeo-square", title: "Viadeo square"},
        {name:"fab fa-viber", title: "Viber"},
        {name:"fab fa-vimeo", title: "Vimeo"},
        {name:"fab fa-vimeo-square", title: "Vimeo square"},
        {name:"fab fa-vimeo-v", title: "Vimeo v"},
        {name:"fab fa-vine", title: "Vine"},
        {name:"fab fa-vk", title: "Vk"},
        {name:"fab fa-vnv", title: "Vnv"},
        {name:"fab fa-vuejs", title: "Vuejs"},
        {name:"fab fa-waze", title: "Waze"},
        {name:"fab fa-weebly", title: "Weebly"},
        {name:"fab fa-weibo", title: "Weibo"},
        {name:"fab fa-weixin", title: "Weixin"},
        {name:"fab fa-whatsapp", title: "Whatsapp"},
        {name:"fab fa-whatsapp-square", title: "Whatsapp square"},
        {name:"fab fa-whmcs", title: "Whmcs"},
        {name:"fab fa-wikipedia-w", title: "Wikipedia w"},
        {name:"fab fa-windows", title: "Windows"},
        {name:"fab fa-wix", title: "Wix"},
        {name:"fab fa-wizards-of-the-coast", title: "Wizards of the coast"},
        {name:"fab fa-wolf-pack-battalion", title: "Wolf pack battalion"},
        {name:"fab fa-wordpress", title: "Wordpress"},
        {name:"fab fa-wordpress-simple", title: "Wordpress simple"},
        {name:"fab fa-wpbeginner", title: "Wpbeginner"},
        {name:"fab fa-wpexplorer", title: "Wpexplorer"},
        {name:"fab fa-wpforms", title: "Wpforms"},
        {name:"fab fa-wpressr", title: "Wpressr"},
        {name:"fab fa-xbox", title: "Xbox"},
        {name:"fab fa-xing", title: "Xing"},
        {name:"fab fa-xing-square", title: "Xing square"},
        {name:"fab fa-y-combinator", title: "Y combinator"},
        {name:"fab fa-yahoo", title: "Yahoo"},
        {name:"fab fa-yammer", title: "Yammer"},
        {name:"fab fa-yandex", title: "Yandex"},
        {name:"fab fa-yandex-international", title: "Yandex international"},
        {name:"fab fa-yarn", title: "Yarn"},
        {name:"fab fa-yelp", title: "Yelp"},
        {name:"fab fa-yoast", title: "Yoast"},
        {name:"fab fa-youtube", title: "Youtube"},
        {name:"fab fa-youtube-square", title: "Youtube square"},
        {name:"fab fa-zhihu", title: "Zhihu"},
    ]
}